// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unifesspa.UniPlus.Geo.Infrastructure.Persistence;

#nullable disable

namespace Unifesspa.UniPlus.Geo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GeoDbContext))]
    partial class GeoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.Bairro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cidade_id");

                    b.Property<Point>("Coordenada")
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("coordenada");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdOrigemDne")
                        .HasColumnType("text")
                        .HasColumnName("id_origem_dne");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_normalizado");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersaoDataset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_dataset");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id")
                        .HasName("pk_bairro");

                    b.HasIndex("Coordenada")
                        .HasDatabaseName("ix_bairro_coordenada");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Coordenada"), "gist");

                    b.HasIndex("VersaoDataset")
                        .HasDatabaseName("ix_bairro_versao_dataset");

                    b.HasIndex("CidadeId", "NomeNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ix_bairro_cidade_nome");

                    b.ToTable("bairro", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.BairroFaixaCep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BairroId")
                        .HasColumnType("uuid")
                        .HasColumnName("bairro_id");

                    b.Property<string>("CepFinal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep_final");

                    b.Property<string>("CepInicial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep_inicial");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersaoDataset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_dataset");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id")
                        .HasName("pk_bairro_faixa_cep");

                    b.HasIndex("VersaoDataset")
                        .HasDatabaseName("ix_bairro_faixa_cep_versao_dataset");

                    b.HasIndex("BairroId", "CepInicial", "CepFinal")
                        .IsUnique()
                        .HasDatabaseName("ix_bairro_faixa_cep_natural");

                    b.ToTable("bairro_faixa_cep", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.CepGrandeUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .HasColumnType("text")
                        .HasColumnName("nome_normalizado");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersaoDataset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_dataset");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id")
                        .HasName("pk_cep_grande_usuario");

                    b.HasIndex("Cep")
                        .IsUnique()
                        .HasDatabaseName("ix_cep_grande_usuario_cep");

                    b.HasIndex("VersaoDataset")
                        .HasDatabaseName("ix_cep_grande_usuario_versao_dataset");

                    b.ToTable("cep_grande_usuario", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoIbge")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_ibge");

                    b.Property<Point>("Coordenada")
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("coordenada");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Ddd")
                        .HasColumnType("text")
                        .HasColumnName("ddd");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estado_id");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("MesorregiaoCodigo")
                        .HasColumnType("text")
                        .HasColumnName("mesorregiao_codigo");

                    b.Property<string>("MesorregiaoNome")
                        .HasColumnType("text")
                        .HasColumnName("mesorregiao_nome");

                    b.Property<string>("MicrorregiaoCodigo")
                        .HasColumnType("text")
                        .HasColumnName("microrregiao_codigo");

                    b.Property<string>("MicrorregiaoNome")
                        .HasColumnType("text")
                        .HasColumnName("microrregiao_nome");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .HasColumnType("text")
                        .HasColumnName("nome_normalizado");

                    b.Property<string>("RegiaoImediataCodigo")
                        .HasColumnType("text")
                        .HasColumnName("regiao_imediata_codigo");

                    b.Property<string>("RegiaoImediataNome")
                        .HasColumnType("text")
                        .HasColumnName("regiao_imediata_nome");

                    b.Property<string>("RegiaoIntermediariaCodigo")
                        .HasColumnType("text")
                        .HasColumnName("regiao_intermediaria_codigo");

                    b.Property<string>("RegiaoIntermediariaNome")
                        .HasColumnType("text")
                        .HasColumnName("regiao_intermediaria_nome");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersaoDataset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_dataset");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id")
                        .HasName("pk_cidade");

                    b.HasIndex("CodigoIbge")
                        .IsUnique()
                        .HasDatabaseName("ix_cidade_codigo_ibge");

                    b.HasIndex("Coordenada")
                        .HasDatabaseName("ix_cidade_coordenada");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Coordenada"), "gist");

                    b.HasIndex("EstadoId")
                        .HasDatabaseName("ix_cidade_estado_id");

                    b.HasIndex("NomeNormalizado")
                        .HasDatabaseName("ix_cidade_nome_normalizado_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NomeNormalizado"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NomeNormalizado"), new[] { "gin_trgm_ops" });

                    b.HasIndex("VersaoDataset")
                        .HasDatabaseName("ix_cidade_versao_dataset");

                    b.ToTable("cidade", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.CidadeFaixaCep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CepFinal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep_final");

                    b.Property<string>("CepInicial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep_inicial");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cidade_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersaoDataset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_dataset");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id")
                        .HasName("pk_cidade_faixa_cep");

                    b.HasIndex("VersaoDataset")
                        .HasDatabaseName("ix_cidade_faixa_cep_versao_dataset");

                    b.HasIndex("CidadeId", "CepInicial", "CepFinal")
                        .IsUnique()
                        .HasDatabaseName("ix_cidade_faixa_cep_natural");

                    b.ToTable("cidade_faixa_cep", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.CidadeIndicador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aniversario")
                        .HasColumnType("text")
                        .HasColumnName("aniversario");

                    b.Property<decimal?>("AreaKm2")
                        .HasColumnType("numeric")
                        .HasColumnName("area_km2");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cidade_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DensidadeDemografica")
                        .HasColumnType("numeric")
                        .HasColumnName("densidade_demografica");

                    b.Property<decimal?>("Despesas")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("despesas");

                    b.Property<decimal?>("Escolarizacao6a14")
                        .HasColumnType("numeric")
                        .HasColumnName("escolarizacao_6_a_14");

                    b.Property<string>("Gentilico")
                        .HasColumnType("text")
                        .HasColumnName("gentilico");

                    b.Property<decimal?>("Idh")
                        .HasColumnType("numeric")
                        .HasColumnName("idh");

                    b.Property<decimal?>("MortalidadeInfantil")
                        .HasColumnType("numeric")
                        .HasColumnName("mortalidade_infantil");

                    b.Property<decimal?>("PibPerCapita")
                        .HasColumnType("numeric")
                        .HasColumnName("pib_per_capita");

                    b.Property<int?>("PopulacaoResidente")
                        .HasColumnType("integer")
                        .HasColumnName("populacao_residente");

                    b.Property<string>("Prefeito")
                        .HasColumnType("text")
                        .HasColumnName("prefeito");

                    b.Property<decimal?>("Receitas")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("receitas");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersaoDataset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_dataset");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id")
                        .HasName("pk_cidade_indicador");

                    b.HasIndex("CidadeId")
                        .IsUnique()
                        .HasDatabaseName("ix_cidade_indicador_cidade_id");

                    b.HasIndex("VersaoDataset")
                        .HasDatabaseName("ix_cidade_indicador_versao_dataset");

                    b.ToTable("cidade_indicador", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.Distrito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cidade_id");

                    b.Property<Point>("Coordenada")
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("coordenada");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdOrigemDne")
                        .HasColumnType("text")
                        .HasColumnName("id_origem_dne");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_normalizado");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersaoDataset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_dataset");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id")
                        .HasName("pk_distrito");

                    b.HasIndex("Coordenada")
                        .HasDatabaseName("ix_distrito_coordenada");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Coordenada"), "gist");

                    b.HasIndex("VersaoDataset")
                        .HasDatabaseName("ix_distrito_versao_dataset");

                    b.HasIndex("CidadeId", "NomeNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ix_distrito_cidade_nome");

                    b.ToTable("distrito", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.DistritoFaixaCep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CepFinal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep_final");

                    b.Property<string>("CepInicial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep_inicial");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DistritoId")
                        .HasColumnType("uuid")
                        .HasColumnName("distrito_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersaoDataset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_dataset");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id")
                        .HasName("pk_distrito_faixa_cep");

                    b.HasIndex("VersaoDataset")
                        .HasDatabaseName("ix_distrito_faixa_cep_versao_dataset");

                    b.HasIndex("DistritoId", "CepInicial", "CepFinal")
                        .IsUnique()
                        .HasDatabaseName("ix_distrito_faixa_cep_natural");

                    b.ToTable("distrito_faixa_cep", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capital")
                        .HasColumnType("text")
                        .HasColumnName("capital");

                    b.Property<string>("CepFinal")
                        .HasColumnType("text")
                        .HasColumnName("cep_final");

                    b.Property<string>("CepInicial")
                        .HasColumnType("text")
                        .HasColumnName("cep_inicial");

                    b.Property<string>("CodigoIbge")
                        .HasColumnType("text")
                        .HasColumnName("codigo_ibge");

                    b.Property<Point>("Coordenada")
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("coordenada");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .HasColumnType("text")
                        .HasColumnName("nome_normalizado");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("uuid")
                        .HasColumnName("pais_id");

                    b.Property<string>("Regiao")
                        .HasColumnType("text")
                        .HasColumnName("regiao");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersaoDataset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_dataset");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id")
                        .HasName("pk_estado");

                    b.HasIndex("Coordenada")
                        .HasDatabaseName("ix_estado_coordenada");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Coordenada"), "gist");

                    b.HasIndex("PaisId")
                        .HasDatabaseName("ix_estado_pais_id");

                    b.HasIndex("Uf")
                        .IsUnique()
                        .HasDatabaseName("ix_estado_uf");

                    b.HasIndex("VersaoDataset")
                        .HasDatabaseName("ix_estado_versao_dataset");

                    b.ToTable("estado", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.EstadoFaixaCep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CepFinal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep_final");

                    b.Property<string>("CepInicial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep_inicial");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estado_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersaoDataset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_dataset");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id")
                        .HasName("pk_estado_faixa_cep");

                    b.HasIndex("VersaoDataset")
                        .HasDatabaseName("ix_estado_faixa_cep_versao_dataset");

                    b.HasIndex("EstadoId", "CepInicial", "CepFinal")
                        .IsUnique()
                        .HasDatabaseName("ix_estado_faixa_cep_natural");

                    b.ToTable("estado_faixa_cep", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.EstadoIndicador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AreaKm2")
                        .HasColumnType("numeric")
                        .HasColumnName("area_km2");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DensidadeDemografica")
                        .HasColumnType("numeric")
                        .HasColumnName("densidade_demografica");

                    b.Property<decimal?>("DespesasBrutas")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("despesas_brutas");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estado_id");

                    b.Property<string>("Gentilico")
                        .HasColumnType("text")
                        .HasColumnName("gentilico");

                    b.Property<string>("Governador")
                        .HasColumnType("text")
                        .HasColumnName("governador");

                    b.Property<decimal?>("Idh")
                        .HasColumnType("numeric")
                        .HasColumnName("idh");

                    b.Property<int?>("MatriculasEnsinoFundamental2023")
                        .HasColumnType("integer")
                        .HasColumnName("matriculas_ensino_fundamental_2023");

                    b.Property<int?>("PopulacaoResidente2022")
                        .HasColumnType("integer")
                        .HasColumnName("populacao_residente_2022");

                    b.Property<decimal?>("ReceitasBrutas")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("receitas_brutas");

                    b.Property<int?>("RendimentoMensalPerCapita")
                        .HasColumnType("integer")
                        .HasColumnName("rendimento_mensal_per_capita");

                    b.Property<int?>("TotalVeiculos2023")
                        .HasColumnType("integer")
                        .HasColumnName("total_veiculos_2023");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersaoDataset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_dataset");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id")
                        .HasName("pk_estado_indicador");

                    b.HasIndex("EstadoId")
                        .IsUnique()
                        .HasDatabaseName("ix_estado_indicador_estado_id");

                    b.HasIndex("VersaoDataset")
                        .HasDatabaseName("ix_estado_indicador_versao_dataset");

                    b.ToTable("estado_indicador", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.Logradouro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid?>("BairroId")
                        .HasColumnType("uuid")
                        .HasColumnName("bairro_id");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cidade_id");

                    b.Property<Point>("Coordenada")
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("coordenada");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DistritoId")
                        .HasColumnType("uuid")
                        .HasColumnName("distrito_id");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("text")
                        .HasColumnName("nome_completo");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_normalizado");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersaoDataset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_dataset");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id")
                        .HasName("pk_logradouro");

                    b.HasIndex("BairroId")
                        .HasDatabaseName("ix_logradouro_bairro_id");

                    b.HasIndex("CidadeId")
                        .HasDatabaseName("ix_logradouro_cidade_id");

                    b.HasIndex("Coordenada")
                        .HasDatabaseName("ix_logradouro_coordenada");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Coordenada"), "gist");

                    b.HasIndex("DistritoId")
                        .HasDatabaseName("ix_logradouro_distrito_id");

                    b.HasIndex("NomeNormalizado")
                        .HasDatabaseName("ix_logradouro_nome_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NomeNormalizado"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NomeNormalizado"), new[] { "gin_trgm_ops" });

                    b.HasIndex("VersaoDataset")
                        .HasDatabaseName("ix_logradouro_versao_dataset");

                    b.HasIndex("Cep", "NomeNormalizado", "CidadeId")
                        .IsUnique()
                        .HasDatabaseName("ix_logradouro_natural");

                    b.ToTable("logradouro", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.LogradouroComplemento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<string>("ComplementoNormalizado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complemento_normalizado");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersaoDataset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_dataset");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id")
                        .HasName("pk_logradouro_complemento");

                    b.HasIndex("VersaoDataset")
                        .HasDatabaseName("ix_logradouro_complemento_versao_dataset");

                    b.HasIndex("Cep", "ComplementoNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ux_logradouro_complemento_cep_complemento");

                    b.ToTable("logradouro_complemento", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.Pais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoBcb")
                        .HasColumnType("text")
                        .HasColumnName("codigo_bcb");

                    b.Property<string>("CodigoRfb")
                        .HasColumnType("text")
                        .HasColumnName("codigo_rfb");

                    b.Property<string>("CodigoSiscomex")
                        .HasColumnType("text")
                        .HasColumnName("codigo_siscomex");

                    b.Property<string>("CodigoSped")
                        .HasColumnType("text")
                        .HasColumnName("codigo_sped");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sigla");

                    b.Property<string>("SiglaIso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sigla_iso");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersaoDataset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_dataset");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id")
                        .HasName("pk_pais");

                    b.HasIndex("SiglaIso")
                        .IsUnique()
                        .HasDatabaseName("ix_pais_sigla_iso");

                    b.HasIndex("VersaoDataset")
                        .HasDatabaseName("ix_pais_versao_dataset");

                    b.ToTable("pais", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Infrastructure.Core.Idempotency.IdempotencyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("body_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("idempotency_key");

                    b.Property<byte[]>("ResponseBodyCipher")
                        .HasColumnType("bytea")
                        .HasColumnName("response_body_cipher");

                    b.Property<string>("ResponseHeadersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_headers_json");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("scope");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_cache");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_idempotency_expires_at");

                    b.HasIndex("Scope", "Endpoint", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("idx_idempotency_lookup");

                    b.ToTable("idempotency_cache", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.Bairro", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Geo.Domain.Entities.Cidade", null)
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bairro_cidades_cidade_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.BairroFaixaCep", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Geo.Domain.Entities.Bairro", null)
                        .WithMany()
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bairro_faixa_cep_bairro_bairro_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.Cidade", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Geo.Domain.Entities.Estado", null)
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cidade_estados_estado_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.CidadeFaixaCep", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Geo.Domain.Entities.Cidade", null)
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cidade_faixa_cep_cidade_cidade_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.CidadeIndicador", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Geo.Domain.Entities.Cidade", null)
                        .WithOne()
                        .HasForeignKey("Unifesspa.UniPlus.Geo.Domain.Entities.CidadeIndicador", "CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cidade_indicador_cidade_cidade_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.Distrito", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Geo.Domain.Entities.Cidade", null)
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_distrito_cidade_cidade_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.DistritoFaixaCep", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Geo.Domain.Entities.Distrito", null)
                        .WithMany()
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_distrito_faixa_cep_distrito_distrito_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.Estado", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Geo.Domain.Entities.Pais", null)
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_estado_paises_pais_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.EstadoFaixaCep", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Geo.Domain.Entities.Estado", null)
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_estado_faixa_cep_estado_estado_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.EstadoIndicador", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Geo.Domain.Entities.Estado", null)
                        .WithOne()
                        .HasForeignKey("Unifesspa.UniPlus.Geo.Domain.Entities.EstadoIndicador", "EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_estado_indicador_estado_estado_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Geo.Domain.Entities.Logradouro", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Geo.Domain.Entities.Bairro", null)
                        .WithMany()
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_logradouro_bairro_bairro_id");

                    b.HasOne("Unifesspa.UniPlus.Geo.Domain.Entities.Cidade", null)
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_logradouro_cidade_cidade_id");

                    b.HasOne("Unifesspa.UniPlus.Geo.Domain.Entities.Distrito", null)
                        .WithMany()
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_logradouro_distrito_distrito_id");
                });
#pragma warning restore 612, 618
        }
    }
}
