// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unifesspa.UniPlus.Configuracao.Infrastructure.Persistence;

#nullable disable

namespace Unifesspa.UniPlus.Configuracao.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConfiguracaoDbContext))]
    [Migration("20260617210624_AddCampusELocalOferta")]
    partial class AddCampusELocalOferta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Unifesspa.UniPlus.Configuracao.Domain.Entities.Campus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("character(8)")
                        .HasColumnName("cep")
                        .IsFixedLength();

                    b.Property<string>("CidadeCodigoIbge")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .HasColumnName("cidade_codigo_ibge")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("CidadeDisplayAtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cidade_display_atualizado_em");

                    b.Property<string>("CidadeNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("cidade_nome");

                    b.Property<string>("CidadeOrigem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cidade_origem");

                    b.Property<string>("CidadeUf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("cidade_uf")
                        .IsFixedLength();

                    b.Property<string>("CodigoEmec")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_emec");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endereco");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sigla");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_campus");

                    b.HasIndex("CidadeCodigoIbge")
                        .HasDatabaseName("ix_campus_cidade_codigo_ibge");

                    b.HasIndex("Sigla")
                        .IsUnique()
                        .HasDatabaseName("ix_campus_sigla_vivo")
                        .HasFilter("is_deleted = false");

                    b.ToTable("campus", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Configuracao.Domain.Entities.LocalOferta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CampusResponsavelId")
                        .HasColumnType("uuid")
                        .HasColumnName("campus_responsavel_id");

                    b.Property<string>("CidadeCodigoIbge")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .HasColumnName("cidade_codigo_ibge")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("CidadeDisplayAtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cidade_display_atualizado_em");

                    b.Property<string>("CidadeNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("cidade_nome");

                    b.Property<string>("CidadeOrigem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cidade_origem");

                    b.Property<string>("CidadeUf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("cidade_uf")
                        .IsFixedLength();

                    b.Property<string>("CodigoEmec")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_emec");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endereco");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_local_oferta");

                    b.HasIndex("CampusResponsavelId")
                        .HasDatabaseName("ix_local_oferta_campus_responsavel_id");

                    b.HasIndex("CidadeCodigoIbge")
                        .HasDatabaseName("ix_local_oferta_cidade_codigo_ibge");

                    b.ToTable("local_oferta", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Infrastructure.Core.Idempotency.IdempotencyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("body_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("idempotency_key");

                    b.Property<byte[]>("ResponseBodyCipher")
                        .HasColumnType("bytea")
                        .HasColumnName("response_body_cipher");

                    b.Property<string>("ResponseHeadersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_headers_json");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("scope");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_cache");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_idempotency_expires_at");

                    b.HasIndex("Scope", "Endpoint", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("idx_idempotency_lookup");

                    b.ToTable("idempotency_cache", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Configuracao.Domain.Entities.LocalOferta", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Configuracao.Domain.Entities.Campus", null)
                        .WithMany()
                        .HasForeignKey("CampusResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_local_oferta_campus_campus_responsavel_id");
                });
#pragma warning restore 612, 618
        }
    }
}
