// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unifesspa.UniPlus.OrganizacaoInstitucional.Infrastructure.Persistence;

#nullable disable

namespace Unifesspa.UniPlus.OrganizacaoInstitucional.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrganizacaoInstitucionalDbContext))]
    [Migration("20260625190814_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organizacao")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Unifesspa.UniPlus.Infrastructure.Core.Idempotency.IdempotencyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("body_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("idempotency_key");

                    b.Property<byte[]>("ResponseBodyCipher")
                        .HasColumnType("bytea")
                        .HasColumnName("response_body_cipher");

                    b.Property<string>("ResponseHeadersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_headers_json");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("scope");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_cache");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_idempotency_expires_at");

                    b.HasIndex("Scope", "Endpoint", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("idx_idempotency_lookup");

                    b.ToTable("idempotency_cache", "organizacao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.OrganizacaoInstitucional.Domain.Entities.Instituicao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AtoCredenciamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ato_credenciamento");

                    b.Property<string>("AtoRecredenciamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ato_recredenciamento");

                    b.Property<string>("CategoriaAdministrativa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria_administrativa");

                    b.Property<string>("CidadeCodigoIbge")
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .HasColumnName("cidade_codigo_ibge")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("CidadeDisplayAtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cidade_display_atualizado_em");

                    b.Property<string>("CidadeNome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("cidade_nome");

                    b.Property<string>("CidadeOrigem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cidade_origem");

                    b.Property<string>("CidadeUf")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("cidade_uf")
                        .IsFixedLength();

                    b.Property<string>("Cnpj")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CodigoEmec")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_emec");

                    b.Property<string>("CodigoMantenedoraEmec")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_mantenedora_emec");

                    b.Property<string>("ConceitoInstitucional")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("conceito_institucional");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Igc")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("igc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Mantenedora")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("mantenedora");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome");

                    b.Property<string>("OrganizacaoAcademica")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organizacao_academica");

                    b.Property<bool>("RegistroVivoSentinela")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("registro_vivo_sentinela");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sigla");

                    b.Property<string>("Situacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("situacao");

                    b.Property<Guid?>("UnidadeRaizId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_raiz_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("updated_by");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_instituicao");

                    b.HasIndex("CidadeCodigoIbge")
                        .HasDatabaseName("ix_instituicao_cidade_codigo_ibge");

                    b.HasIndex("RegistroVivoSentinela")
                        .IsUnique()
                        .HasDatabaseName("ix_instituicao_singleton_vivo")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("UnidadeRaizId")
                        .HasDatabaseName("ix_instituicao_unidade_raiz_id");

                    b.ToTable("instituicao", "organizacao", t =>
                        {
                            t.HasCheckConstraint("ck_instituicao_cidade_completa", "(cidade_codigo_ibge IS NULL AND cidade_nome IS NULL AND cidade_uf IS NULL) OR (cidade_codigo_ibge IS NOT NULL AND cidade_nome IS NOT NULL AND cidade_uf IS NOT NULL)");

                            t.HasCheckConstraint("ck_instituicao_cidade_obrigatoria_com_endereco", "endereco_cep IS NULL OR cidade_codigo_ibge IS NOT NULL");

                            t.HasCheckConstraint("ck_instituicao_endereco_cidade_coerente", "endereco_cidade_codigo_ibge IS NULL OR cidade_codigo_ibge IS NULL OR (endereco_cidade_codigo_ibge = cidade_codigo_ibge AND endereco_cidade_uf IS NOT NULL AND cidade_uf IS NOT NULL AND endereco_cidade_uf = cidade_uf)");

                            t.HasCheckConstraint("ck_instituicao_endereco_completo", "(endereco_cep IS NULL AND endereco_cidade_codigo_ibge IS NULL AND endereco_cidade_nome IS NULL AND endereco_cidade_uf IS NULL AND endereco_nivel_resolucao IS NULL AND endereco_origem IS NULL AND endereco_logradouro IS NULL AND endereco_numero IS NULL AND endereco_complemento IS NULL AND endereco_bairro IS NULL AND endereco_distrito IS NULL AND endereco_latitude IS NULL AND endereco_longitude IS NULL) OR (endereco_cep IS NOT NULL AND endereco_cidade_codigo_ibge IS NOT NULL AND endereco_cidade_nome IS NOT NULL AND endereco_cidade_uf IS NOT NULL AND endereco_nivel_resolucao IS NOT NULL AND endereco_origem IS NOT NULL)");

                            t.HasCheckConstraint("ck_instituicao_singleton_sentinela", "registro_vivo_sentinela = true");
                        });
                });

            modelBuilder.Entity("Unifesspa.UniPlus.OrganizacaoInstitucional.Domain.Entities.Unidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alias");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origem");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sigla");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<bool>("UnidadeAcademica")
                        .HasColumnType("boolean")
                        .HasColumnName("unidade_academica");

                    b.Property<Guid?>("UnidadeSuperiorId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_superior_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly?>("VigenciaFim")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_fim");

                    b.Property<DateOnly>("VigenciaInicio")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_inicio");

                    b.HasKey("Id")
                        .HasName("pk_unidade");

                    b.HasIndex("Alias")
                        .HasDatabaseName("ix_unidade_alias");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_unidade_codigo_vivo")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("Sigla")
                        .IsUnique()
                        .HasDatabaseName("ix_unidade_sigla_vivo")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_unidade_slug_vivo")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("UnidadeSuperiorId")
                        .HasDatabaseName("ix_unidade_superior_id");

                    b.ToTable("unidade", "organizacao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.OrganizacaoInstitucional.Domain.Entities.UnidadeIdentificadorHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MotivoMudanca")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_mudanca");

                    b.Property<string>("TipoIdentificador")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_identificador");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("valor");

                    b.Property<DateOnly?>("VigenciaFim")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_fim");

                    b.Property<DateOnly>("VigenciaInicio")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_inicio");

                    b.HasKey("Id")
                        .HasName("pk_unidade_identificador_historico");

                    b.HasIndex("UnidadeId", "TipoIdentificador", "VigenciaInicio")
                        .HasDatabaseName("ix_uid_hist_unidade_tipo_inicio");

                    b.ToTable("unidade_identificador_historico", "organizacao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.OrganizacaoInstitucional.Domain.Entities.Instituicao", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.OrganizacaoInstitucional.Domain.Entities.Unidade", null)
                        .WithMany()
                        .HasForeignKey("UnidadeRaizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_instituicao_unidades_unidade_raiz_id");

                    b.OwnsOne("Unifesspa.UniPlus.Kernel.Domain.Enderecos.ReferenciaEnderecoGeo", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("InstituicaoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Bairro")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("endereco_bairro");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character(8)")
                                .HasColumnName("endereco_cep")
                                .IsFixedLength();

                            b1.Property<string>("CidadeCodigoIbge")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character(7)")
                                .HasColumnName("endereco_cidade_codigo_ibge")
                                .IsFixedLength();

                            b1.Property<string>("CidadeNome")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("endereco_cidade_nome");

                            b1.Property<string>("CidadeUf")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("endereco_cidade_uf")
                                .IsFixedLength();

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("endereco_complemento");

                            b1.Property<DateTimeOffset?>("DisplayAtualizadoEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("endereco_display_atualizado_em");

                            b1.Property<string>("Distrito")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("endereco_distrito");

                            b1.Property<decimal?>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("endereco_latitude");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("endereco_logradouro");

                            b1.Property<decimal?>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("endereco_longitude");

                            b1.Property<string>("NivelResolucao")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("endereco_nivel_resolucao");

                            b1.Property<string>("Numero")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("endereco_numero");

                            b1.Property<string>("Origem")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("endereco_origem");

                            b1.HasKey("InstituicaoId");

                            b1.ToTable("instituicao", "organizacao");

                            b1.WithOwner()
                                .HasForeignKey("InstituicaoId")
                                .HasConstraintName("fk_instituicao_instituicao_id");
                        });

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.OrganizacaoInstitucional.Domain.Entities.Unidade", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.OrganizacaoInstitucional.Domain.Entities.Unidade", null)
                        .WithMany()
                        .HasForeignKey("UnidadeSuperiorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_unidade_unidade_unidade_superior_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.OrganizacaoInstitucional.Domain.Entities.UnidadeIdentificadorHistorico", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.OrganizacaoInstitucional.Domain.Entities.Unidade", null)
                        .WithMany("Historico")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired()
                        .HasConstraintName("fk_unidade_identificador_historico_unidade_unidade_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.OrganizacaoInstitucional.Domain.Entities.Unidade", b =>
                {
                    b.Navigation("Historico");
                });
#pragma warning restore 612, 618
        }
    }
}
