// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unifesspa.UniPlus.Ingresso.Infrastructure.Persistence;

#nullable disable

namespace Unifesspa.UniPlus.Ingresso.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IngressoDbContext))]
    partial class IngressoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Unifesspa.UniPlus.Ingresso.Domain.Entities.Chamada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DataPublicacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_publicacao");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("EditalId")
                        .HasColumnType("uuid")
                        .HasColumnName("edital_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<DateTimeOffset>("PrazoManifestacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prazo_manifestacao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_chamadas");

                    b.HasIndex("EditalId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_chamadas_edital_id_numero");

                    b.ToTable("chamadas", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Ingresso.Domain.Entities.Convocacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidato_id");

                    b.Property<Guid>("ChamadaId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamada_id");

                    b.Property<string>("CodigoCurso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_curso");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DataManifestacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_manifestacao");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("InscricaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("inscricao_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Posicao")
                        .HasColumnType("integer")
                        .HasColumnName("posicao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_convocacoes");

                    b.HasIndex("ChamadaId")
                        .HasDatabaseName("ix_convocacoes_chamada_id");

                    b.ToTable("convocacoes", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Ingresso.Domain.Entities.DocumentoMatricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CaminhoStorage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("caminho_storage");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("uuid")
                        .HasColumnName("matricula_id");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo_rejeicao");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nome_arquivo");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_documento");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("Validado")
                        .HasColumnType("boolean")
                        .HasColumnName("validado");

                    b.HasKey("Id")
                        .HasName("pk_documentos_matricula");

                    b.HasIndex("MatriculaId")
                        .HasDatabaseName("ix_documentos_matricula_matricula_id");

                    b.ToTable("documentos_matricula", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Ingresso.Domain.Entities.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidato_id");

                    b.Property<string>("CodigoCurso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_curso");

                    b.Property<Guid>("ConvocacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("convocacao_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_matriculas");

                    b.ToTable("matriculas", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Ingresso.Domain.Entities.Convocacao", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Ingresso.Domain.Entities.Chamada", null)
                        .WithMany("Convocacoes")
                        .HasForeignKey("ChamadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_convocacoes_chamadas_chamada_id");

                    b.OwnsOne("Unifesspa.UniPlus.Ingresso.Domain.ValueObjects.ProtocoloConvocacao", "Protocolo", b1 =>
                        {
                            b1.Property<Guid>("ConvocacaoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("protocolo");

                            b1.HasKey("ConvocacaoId");

                            b1.HasIndex("Valor")
                                .IsUnique()
                                .HasDatabaseName("ix_convocacoes_protocolo");

                            b1.ToTable("convocacoes");

                            b1.WithOwner()
                                .HasForeignKey("ConvocacaoId")
                                .HasConstraintName("fk_convocacoes_convocacoes_id");
                        });

                    b.Navigation("Protocolo")
                        .IsRequired();
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Ingresso.Domain.Entities.DocumentoMatricula", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Ingresso.Domain.Entities.Matricula", null)
                        .WithMany("Documentos")
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documentos_matricula_matriculas_matricula_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Ingresso.Domain.Entities.Chamada", b =>
                {
                    b.Navigation("Convocacoes");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Ingresso.Domain.Entities.Matricula", b =>
                {
                    b.Navigation("Documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
