apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-selecao-api
  labels:
    app: {{ .Release.Name }}-selecao-api
    app.kubernetes.io/name: uniplus-selecao
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-selecao-api
