// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unifesspa.UniPlus.Discentes.Infrastructure.Persistence;

#nullable disable

namespace Unifesspa.UniPlus.Discentes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DiscentesDbContext))]
    partial class DiscentesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("discentes")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Unifesspa.UniPlus.Discentes.Domain.Entities.SyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("ProcessedItems")
                        .HasColumnType("integer")
                        .HasColumnName("processed_items");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("success_count");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer")
                        .HasColumnName("total_items");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sync_run");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_sync_run_started_at");

                    b.ToTable("sync_run", "discentes");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Discentes.Infrastructure.Persistence.Records.VinculoDiscenteRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AnoIngresso")
                        .HasColumnType("integer")
                        .HasColumnName("ano_ingresso");

                    b.Property<byte[]>("CpfCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("cpf_ciphertext");

                    b.Property<string>("CursoCodigoEmec")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("curso_codigo_emec");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<string>("CursoNome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("curso_nome");

                    b.Property<int>("CursoUnidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_unidade_id");

                    b.Property<string>("CursoUnidadeNome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("curso_unidade_nome");

                    b.Property<long>("IdDiscenteSigaa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_discente_sigaa");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("matricula");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome");

                    b.Property<int>("PeriodoIngresso")
                        .HasColumnType("integer")
                        .HasColumnName("periodo_ingresso");

                    b.Property<string>("SituacaoDescricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("situacao_descricao");

                    b.Property<int>("SituacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("situacao_id");

                    b.Property<string>("SituacaoVinculo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("situacao_vinculo");

                    b.HasKey("Id")
                        .HasName("pk_vinculo_discente");

                    b.HasIndex("IdDiscenteSigaa")
                        .IsUnique()
                        .HasDatabaseName("ix_vinculo_discente_id_discente_sigaa");

                    b.ToTable("vinculo_discente", "discentes");
                });
#pragma warning restore 612, 618
        }
    }
}
