namespace Unifesspa.UniPlus.PermissionCatalogGenerator;

using System.Text;
using System.Text.RegularExpressions;

using YamlDotNet.Core;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

/// <summary>
/// Lê o catálogo declarativo de permissões e produz o contrato .NET consumido
/// pelo ponto de decisão de acesso. O formato YAML aceito é deliberadamente
/// restrito ao schema versionado em <c>permissions.yml</c>.
/// </summary>
public static class CatalogoPermissoesGerador
{
    private static readonly Regex SegmentoCodigoPermissaoRegex = new(
        "^[a-z][a-z0-9-]*$",
        RegexOptions.CultureInvariant);

    private static readonly HashSet<string> SensibilidadesValidas = new(StringComparer.Ordinal)
    {
        "publica",
        "interna",
        "pessoal",
        "sensivel",
    };

    private static readonly HashSet<string> NiveisAuditoriaValidos = new(StringComparer.Ordinal)
    {
        "nenhum",
        "caso-uso",
    };

    private static readonly HashSet<string> CamposContextoValidos = new(StringComparer.Ordinal)
    {
        "recursoTipo",
        "sensibilidade",
        "unidadeProprietariaId",
        "processoId",
        "chamadaId",
    };

    private static readonly HashSet<string> TiposSujeitoValidos = new(StringComparer.Ordinal)
    {
        "servidor",
        "auditor",
        "plataforma_admin",
        "candidato",
        "terceiro",
    };

    // O recorte mínimo não possui checks contextuais adicionais. O check de
    // concessão do PDP é implícito e, conforme a ADR-0080, não integra
    // decision_checks. A introdução de um check novo deve registrá-lo aqui na
    // mesma mudança que implementa o check no backend.
    private static readonly HashSet<string> DecisionChecksRegistrados = new(StringComparer.Ordinal);

    /// <summary>Gera o conteúdo determinístico do contrato .NET a partir de um arquivo.</summary>
    public static string GerarDeArquivo(string caminhoFonte)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(caminhoFonte);

        return Gerar(File.ReadAllText(caminhoFonte));
    }

    /// <summary>Lê e valida uma fonte declarativa a partir de um arquivo.</summary>
    public static IReadOnlyList<EntradaPermissaoCatalogo> LerDeArquivo(string caminhoFonte)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(caminhoFonte);

        return Ler(File.ReadAllText(caminhoFonte));
    }

    /// <summary>Gera o conteúdo determinístico do contrato .NET a partir do YAML.</summary>
    public static string Gerar(string yaml)
    {
        IReadOnlyList<EntradaPermissaoCatalogo> entradas = Ler(yaml);
        var saida = new StringBuilder();

        saida.AppendLine("// <auto-generated />");
        saida.AppendLine("// Gerado por tools/permission-catalog-generator. Não edite manualmente.");
        saida.AppendLine();
        saida.AppendLine("namespace Unifesspa.UniPlus.Authorization;");
        saida.AppendLine();
        saida.AppendLine("using Unifesspa.UniPlus.Authorization.Contracts;");
        saida.AppendLine("using Unifesspa.UniPlus.Authorization.Enums;");
        saida.AppendLine();
        saida.AppendLine("/// <summary>Permissões declaradas no catálogo institucional.</summary>");
        saida.AppendLine("public static class UniPlusPermissions");
        saida.AppendLine("{");

        foreach (EntradaPermissaoCatalogo entrada in entradas.OrderBy(x => x.Codigo, StringComparer.Ordinal))
        {
            string nome = ConverterCodigoEmNomeCSharp(entrada.Codigo);
            saida.Append("    public const string ").Append(nome).Append(" = ")
                .Append(FormatarStringCSharp(entrada.Codigo)).AppendLine(";");
        }

        saida.AppendLine();

        foreach (EntradaPermissaoCatalogo entrada in entradas.OrderBy(x => x.Codigo, StringComparer.Ordinal))
        {
            string nome = ConverterCodigoEmNomeCSharp(entrada.Codigo);
            saida.Append("    public static PermissionRequirement ").Append(nome).Append("Requirement { get; } = ")
                .AppendLine("PermissionRequirement.From(");
            saida.Append("        ").Append(nome).AppendLine(",");
            saida.Append("        Sensibilidade.").Append(ConverterSensibilidadeParaEnum(entrada.Sensibilidade)).AppendLine(",");
            saida.Append("        baseLegalPadrao: ").Append(FormatarStringCSharp(entrada.BaseLegalPadrao)).AppendLine(",");
            saida.Append("        requerMfa: ").Append(entrada.RequiresMfa ? "true" : "false").AppendLine(",");
            saida.Append("        requerDuplaAprovacao: ").Append(entrada.RequiresDualApproval ? "true" : "false").AppendLine(",");
            saida.Append("        escopoContextoObrigatorio: ").Append(FormatarColecaoCSharp(entrada.ContextScope)).AppendLine(",");
            saida.Append("        verificacoesDeContexto: ").Append(FormatarColecaoCSharp(entrada.DecisionChecks)).AppendLine(").Value!;");
            saida.AppendLine();
        }

        saida.AppendLine("}");
        return saida.ToString().ReplaceLineEndings("\n");
    }

    /// <summary>Lê e valida uma fonte declarativa de permissões.</summary>
    public static IReadOnlyList<EntradaPermissaoCatalogo> Ler(string yaml)
    {
        ArgumentNullException.ThrowIfNull(yaml);

        PermissionsFileYaml arquivo = DesserializarCatalogo(yaml);

        if (arquivo.Permissions is null)
        {
            throw new FormatException("A raiz do catálogo deve ser 'permissions:'.");
        }

        if (arquivo.Permissions.Count == 0)
        {
            throw new FormatException("O catálogo deve declarar ao menos uma permissão.");
        }

        EntradaPermissaoCatalogo[] entradas = arquivo.Permissions
            .Select(CriarEntrada)
            .ToArray();

        if (entradas.Select(x => x.Codigo).Distinct(StringComparer.Ordinal).Count() != entradas.Length)
        {
            throw new FormatException("O catálogo não pode declarar códigos de permissão repetidos.");
        }

        IGrouping<string, EntradaPermissaoCatalogo>? colisaoDeNome = entradas
            .GroupBy(x => ConverterCodigoEmNomeCSharp(x.Codigo), StringComparer.Ordinal)
            .FirstOrDefault(grupo => grupo.Count() > 1);
        if (colisaoDeNome is not null)
        {
            string codigosColidentes = string.Join(", ", colisaoDeNome.Select(x => x.Codigo));
            throw new FormatException(
                $"Os códigos de permissão {codigosColidentes} geram o mesmo identificador C# '{colisaoDeNome.Key}' — ajuste a nomenclatura dos segmentos.");
        }

        return entradas.OrderBy(x => x.Codigo, StringComparer.Ordinal).ToArray();
    }

    private static PermissionsFileYaml DesserializarCatalogo(string yaml)
    {
        try
        {
            IDeserializer desserializador = new DeserializerBuilder()
                .WithNamingConvention(UnderscoredNamingConvention.Instance)
                .WithDuplicateKeyChecking()
                .Build();

            // Chave desconhecida na fonte (ex.: campo fora do schema) já
            // falha por padrão — IgnoreUnmatchedProperties() é o único jeito
            // de silenciar isso, e não é chamado aqui de propósito.
            return desserializador.Deserialize<PermissionsFileYaml?>(yaml) ?? new PermissionsFileYaml();
        }
        catch (YamlException ex)
        {
            throw new FormatException($"Catálogo YAML inválido: {ex.Message}", ex);
        }
    }

    private static EntradaPermissaoCatalogo CriarEntrada(EntradaYaml entrada)
    {
        string codigo = ObterTextoObrigatorio(entrada.Codigo, "codigo");
        string modulo = ObterTextoObrigatorio(entrada.Modulo, "modulo");
        string recurso = ObterTextoObrigatorio(entrada.Recurso, "recurso");
        string acao = ObterTextoObrigatorio(entrada.Acao, "acao");
        string descricao = ObterTextoObrigatorio(entrada.Descricao, "descricao");
        string sensibilidade = ObterTextoObrigatorio(entrada.Sensibilidade, "sensibilidade");
        string auditLevel = ObterTextoObrigatorio(entrada.AuditLevel, "audit_level");
        string baseLegalPadrao = ObterTextoPresente(entrada.BaseLegalDefault, "base_legal_default");
        bool experimental = ObterBooleanoObrigatorio(entrada.Experimental, "experimental");
        bool exportavel = ObterBooleanoObrigatorio(entrada.Exportavel, "exportavel");
        bool requiresMfa = ObterBooleanoObrigatorio(entrada.RequiresMfa, "requires_mfa");
        bool requiresDualApproval = ObterBooleanoObrigatorio(entrada.RequiresDualApproval, "requires_dual_approval");
        IReadOnlyList<string> contextScope = ObterListaObrigatoria(entrada.ContextScope, "context_scope");
        IReadOnlyList<string> allowedSubjectKind = ObterListaObrigatoria(entrada.AllowedSubjectKind, "allowed_subject_kind");
        IReadOnlyList<string> decisionChecks = ObterListaObrigatoria(entrada.DecisionChecks, "decision_checks");

        ValidarSegmentoCodigoPermissao(modulo, "modulo");
        ValidarSegmentoCodigoPermissao(recurso, "recurso");
        ValidarSegmentoCodigoPermissao(acao, "acao");

        if (!string.Equals(codigo, $"{modulo}:{recurso}:{acao}", StringComparison.Ordinal))
        {
            throw new FormatException("O código da permissão deve ser composto por modulo:recurso:acao.");
        }

        if (!SensibilidadesValidas.Contains(sensibilidade))
        {
            throw new FormatException($"Sensibilidade inválida: '{sensibilidade}'.");
        }

        if (string.Equals(auditLevel, "cada-acesso", StringComparison.Ordinal))
        {
            throw new FormatException("O nível de auditoria 'cada-acesso' é proibido.");
        }

        if (!NiveisAuditoriaValidos.Contains(auditLevel))
        {
            throw new FormatException($"Nível de auditoria inválido: '{auditLevel}'.");
        }

        if (string.Equals(sensibilidade, "sensivel", StringComparison.Ordinal)
            && string.IsNullOrWhiteSpace(baseLegalPadrao))
        {
            throw new FormatException("Permissão sensível exige base_legal_default.");
        }

        foreach (string tipoSujeito in allowedSubjectKind)
        {
            if (!TiposSujeitoValidos.Contains(tipoSujeito))
            {
                throw new FormatException($"Tipo de sujeito inválido: '{tipoSujeito}'.");
            }
        }

        ValidarSemRepeticao(contextScope, "context_scope");
        ValidarSemRepeticao(allowedSubjectKind, "allowed_subject_kind");
        ValidarSemRepeticao(decisionChecks, "decision_checks");
        ValidarCamposContexto(contextScope);
        ValidarDecisionChecksRegistrados(decisionChecks);

        return new EntradaPermissaoCatalogo(
            codigo,
            modulo,
            recurso,
            acao,
            descricao,
            experimental,
            sensibilidade,
            exportavel,
            auditLevel,
            baseLegalPadrao,
            requiresMfa,
            requiresDualApproval,
            contextScope,
            allowedSubjectKind,
            decisionChecks);
    }

    private static string ObterTextoObrigatorio(string? valor, string nomeCampo)
    {
        string presente = ObterTextoPresente(valor, nomeCampo);
        if (string.IsNullOrWhiteSpace(presente))
        {
            throw new FormatException($"Campo obrigatório vazio: '{nomeCampo}'.");
        }

        return presente;
    }

    // Diferente de ObterTextoObrigatorio: exige a CHAVE presente na fonte,
    // mas aceita valor vazio — base_legal_default: "" é catálogo válido hoje.
    private static string ObterTextoPresente(string? valor, string nomeCampo) =>
        valor ?? throw new FormatException($"Campo obrigatório ausente: '{nomeCampo}'.");

    private static bool ObterBooleanoObrigatorio(bool? valor, string nomeCampo) =>
        valor ?? throw new FormatException($"Campo obrigatório ausente: '{nomeCampo}'.");

    // Elemento null na lista YAML (ex.: "[a,,b]", vírgula sem valor entre
    // duas outras) vira null aqui — distinto de elemento presente com
    // conteúdo vazio ("[\"\"]"), que é uma string vazia real e válida.
    private static List<string> ObterListaObrigatoria(List<string?>? valor, string nomeCampo)
    {
        if (valor is null)
        {
            throw new FormatException($"Campo obrigatório ausente: '{nomeCampo}'.");
        }

        if (valor.Any(elemento => elemento is null))
        {
            throw new FormatException($"Lista YAML não pode conter elementos vazios: '{nomeCampo}'.");
        }

        return valor.ConvertAll(elemento => elemento!);
    }

    private static void ValidarSegmentoCodigoPermissao(string valor, string nomeCampo)
    {
        if (!SegmentoCodigoPermissaoRegex.IsMatch(valor))
        {
            throw new FormatException(
                $"Campo '{nomeCampo}' deve conter um segmento em minúsculas, sem ':', separado apenas por hífens.");
        }
    }

    private static void ValidarSemRepeticao(IEnumerable<string> valores, string nomeCampo)
    {
        if (valores.Distinct(StringComparer.Ordinal).Count() != valores.Count())
        {
            throw new FormatException($"Campo '{nomeCampo}' não pode conter valores repetidos.");
        }
    }

    private static void ValidarCamposContexto(IEnumerable<string> contextScope)
    {
        foreach (string campo in contextScope)
        {
            if (!CamposContextoValidos.Contains(campo))
            {
                throw new FormatException($"Campo de contexto não registrado no backend: '{campo}'.");
            }
        }
    }

    private static void ValidarDecisionChecksRegistrados(IEnumerable<string> decisionChecks)
    {
        foreach (string decisionCheck in decisionChecks)
        {
            if (!DecisionChecksRegistrados.Contains(decisionCheck))
            {
                throw new FormatException($"Decision check não registrado no backend: '{decisionCheck}'.");
            }
        }
    }

    private static string ConverterCodigoEmNomeCSharp(string codigo)
    {
        var nome = new StringBuilder();
        foreach (string segmento in codigo.Split(':'))
        {
            foreach (string palavra in segmento.Split('-', StringSplitOptions.RemoveEmptyEntries))
            {
                nome.Append(char.ToUpperInvariant(palavra[0])).Append(palavra[1..]);
            }
        }

        return nome.ToString();
    }

    private static string ConverterSensibilidadeParaEnum(string sensibilidade) => sensibilidade switch
    {
        "publica" => "Publica",
        "interna" => "Interna",
        "pessoal" => "Pessoal",
        "sensivel" => "Sensivel",
        _ => throw new InvalidOperationException($"Sensibilidade inválida: '{sensibilidade}'."),
    };

    // Um bloco literal YAML (|) ou escape \n dentro de escalar quoted
    // produzem quebra de linha real no valor desserializado — sem escapá-la,
    // o C# gerado teria um newline literal dentro de uma string comum,
    // sintaticamente inválido (só string raw/verbatim aceita isso).
    private static string FormatarStringCSharp(string valor)
    {
        var escapado = new StringBuilder(valor.Length);
        foreach (char caractere in valor)
        {
            escapado.Append(caractere switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                '\0' => "\\0",
                _ => caractere.ToString(),
            });
        }

        return $"\"{escapado}\"";
    }

    private static string FormatarColecaoCSharp(IReadOnlyList<string> valores) => valores.Count == 0
        ? "[]"
        : $"[{string.Join(", ", valores.Select(FormatarStringCSharp))}]";

    // Modelo intermediário da desserialização YAML — todos os campos
    // nullable de propósito: presença/ausência de cada chave é validada
    // explicitamente em CriarEntrada (um bool não-nullable confundiria
    // "ausente" com "false"; uma string não-nullable confundiria "ausente"
    // com string vazia, e base_legal_default: "" é catálogo válido).
    private sealed class PermissionsFileYaml
    {
        public List<EntradaYaml>? Permissions { get; set; }
    }

    private sealed class EntradaYaml
    {
        public string? Codigo { get; set; }

        public string? Modulo { get; set; }

        public string? Recurso { get; set; }

        public string? Acao { get; set; }

        public string? Descricao { get; set; }

        public bool? Experimental { get; set; }

        public string? Sensibilidade { get; set; }

        public bool? Exportavel { get; set; }

        public string? AuditLevel { get; set; }

        public string? BaseLegalDefault { get; set; }

        public bool? RequiresMfa { get; set; }

        public bool? RequiresDualApproval { get; set; }

        public List<string?>? ContextScope { get; set; }

        public List<string?>? AllowedSubjectKind { get; set; }

        public List<string?>? DecisionChecks { get; set; }
    }
}

/// <summary>Representa uma entrada validada do catálogo declarativo.</summary>
public sealed record EntradaPermissaoCatalogo(
    string Codigo,
    string Modulo,
    string Recurso,
    string Acao,
    string Descricao,
    bool Experimental,
    string Sensibilidade,
    bool Exportavel,
    string AuditLevel,
    string BaseLegalPadrao,
    bool RequiresMfa,
    bool RequiresDualApproval,
    IReadOnlyList<string> ContextScope,
    IReadOnlyList<string> AllowedSubjectKind,
    IReadOnlyList<string> DecisionChecks);
