// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unifesspa.UniPlus.Selecao.Infrastructure.Persistence;

#nullable disable

namespace Unifesspa.UniPlus.Selecao.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SelecaoDbContext))]
    [Migration("20260512010258_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Unifesspa.UniPlus.Infrastructure.Core.Idempotency.IdempotencyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("ResponseBodyCipher")
                        .HasColumnType("bytea");

                    b.Property<string>("ResponseHeadersJson")
                        .HasColumnType("jsonb");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_idempotency_expires_at");

                    b.HasIndex("Scope", "Endpoint", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("idx_idempotency_lookup");

                    b.ToTable("idempotency_cache", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Candidato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("candidatos", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Cota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EditalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Modalidade")
                        .HasColumnType("integer");

                    b.Property<decimal>("PercentualVagas")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EditalId");

                    b.ToTable("cotas", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Edital", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BonusRegionalHabilitado")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MaximoOpcoesCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TipoProcesso")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("editais", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Etapa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("EditalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Eliminatoria")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("NotaMinima")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<decimal>("Peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EditalId");

                    b.ToTable("etapas", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Inscricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoCursoPrimeiraOpcao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoCursoSegundaOpcao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("EditalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("ListaEspera")
                        .HasColumnType("boolean");

                    b.Property<int>("Modalidade")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroInscricao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NumeroInscricao")
                        .IsUnique();

                    b.HasIndex("CandidatoId", "EditalId");

                    b.ToTable("inscricoes", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Campus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CodigoCurso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("EditalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("TotalVagas")
                        .HasColumnType("integer");

                    b.Property<string>("Turno")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("processos_seletivos", (string)null);
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Candidato", b =>
                {
                    b.OwnsOne("Unifesspa.UniPlus.Kernel.Domain.ValueObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("CandidatoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("cpf");

                            b1.HasKey("CandidatoId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("candidatos");

                            b1.WithOwner()
                                .HasForeignKey("CandidatoId");
                        });

                    b.OwnsOne("Unifesspa.UniPlus.Kernel.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CandidatoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("email");

                            b1.HasKey("CandidatoId");

                            b1.ToTable("candidatos");

                            b1.WithOwner()
                                .HasForeignKey("CandidatoId");
                        });

                    b.OwnsOne("Unifesspa.UniPlus.Kernel.Domain.ValueObjects.NomeSocial", "NomeSocial", b1 =>
                        {
                            b1.Property<Guid>("CandidatoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Nome")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("nome_social");

                            b1.Property<string>("NomeCivil")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("nome_civil");

                            b1.HasKey("CandidatoId");

                            b1.ToTable("candidatos");

                            b1.WithOwner()
                                .HasForeignKey("CandidatoId");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("NomeSocial")
                        .IsRequired();
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Cota", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.Edital", null)
                        .WithMany("Cotas")
                        .HasForeignKey("EditalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Edital", b =>
                {
                    b.OwnsOne("Unifesspa.UniPlus.Selecao.Domain.ValueObjects.FormulaCalculo", "FormulaCalculo", b1 =>
                        {
                            b1.Property<Guid>("EditalId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BonusRegionalPercentual")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("bonus_regional_percentual");

                            b1.Property<decimal>("FatorDivisao")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("fator_divisao");

                            b1.HasKey("EditalId");

                            b1.ToTable("editais");

                            b1.WithOwner()
                                .HasForeignKey("EditalId");
                        });

                    b.OwnsOne("Unifesspa.UniPlus.Selecao.Domain.ValueObjects.NumeroEdital", "NumeroEdital", b1 =>
                        {
                            b1.Property<Guid>("EditalId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Ano")
                                .HasColumnType("integer")
                                .HasColumnName("ano_edital");

                            b1.Property<int>("Numero")
                                .HasColumnType("integer")
                                .HasColumnName("numero_edital");

                            b1.HasKey("EditalId");

                            b1.ToTable("editais");

                            b1.WithOwner()
                                .HasForeignKey("EditalId");
                        });

                    b.OwnsOne("Unifesspa.UniPlus.Selecao.Domain.ValueObjects.PeriodoInscricao", "PeriodoInscricao", b1 =>
                        {
                            b1.Property<Guid>("EditalId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("Fim")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("periodo_inscricao_fim");

                            b1.Property<DateTimeOffset>("Inicio")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("periodo_inscricao_inicio");

                            b1.HasKey("EditalId");

                            b1.ToTable("editais");

                            b1.WithOwner()
                                .HasForeignKey("EditalId");
                        });

                    b.Navigation("FormulaCalculo");

                    b.Navigation("NumeroEdital")
                        .IsRequired();

                    b.Navigation("PeriodoInscricao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Etapa", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.Edital", null)
                        .WithMany("Etapas")
                        .HasForeignKey("EditalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Edital", b =>
                {
                    b.Navigation("Cotas");

                    b.Navigation("Etapas");
                });
#pragma warning restore 612, 618
        }
    }
}
