// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unifesspa.UniPlus.Selecao.Infrastructure.Persistence;

#nullable disable

namespace Unifesspa.UniPlus.Selecao.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SelecaoDbContext))]
    partial class SelecaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("selecao")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Unifesspa.UniPlus.Infrastructure.Core.Idempotency.IdempotencyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("body_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("idempotency_key");

                    b.Property<byte[]>("ResponseBodyCipher")
                        .HasColumnType("bytea")
                        .HasColumnName("response_body_cipher");

                    b.Property<string>("ResponseHeadersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_headers_json");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("scope");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_cache");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_idempotency_expires_at");

                    b.HasIndex("Scope", "Endpoint", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("idx_idempotency_lookup");

                    b.ToTable("idempotency_cache", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ConfiguracaoBonusRegional", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseLegal")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_legal");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Fator")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("fator");

                    b.Property<string>("MunicipioConvenio")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("municipio_convenio");

                    b.Property<Guid>("ProcessoSeletivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("processo_seletivo_id");

                    b.Property<decimal?>("Teto")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("teto");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_configuracoes_bonus_regional");

                    b.HasIndex("ProcessoSeletivoId")
                        .IsUnique()
                        .HasDatabaseName("ix_configuracoes_bonus_regional_processo_seletivo_id");

                    b.ToTable("configuracoes_bonus_regional", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ConfiguracaoClassificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CasasArredondamento")
                        .HasColumnType("integer")
                        .HasColumnName("casas_arredondamento");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("NOpcoesAlocacao")
                        .HasColumnType("integer")
                        .HasColumnName("n_opcoes_alocacao");

                    b.Property<Guid>("ProcessoSeletivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("processo_seletivo_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_configuracoes_classificacao");

                    b.HasIndex("ProcessoSeletivoId")
                        .IsUnique()
                        .HasDatabaseName("ix_configuracoes_classificacao_processo_seletivo_id");

                    b.ToTable("configuracoes_classificacao", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ConfiguracaoDistribuicaoVagas", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OfertaCursoOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("oferta_curso_origem_id");

                    b.Property<decimal>("Pr")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("pr");

                    b.Property<Guid>("ProcessoSeletivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("processo_seletivo_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VoBase")
                        .HasColumnType("integer")
                        .HasColumnName("vo_base");

                    b.HasKey("Id")
                        .HasName("pk_configuracoes_distribuicao_vagas");

                    b.HasIndex("ProcessoSeletivoId", "OfertaCursoOrigemId")
                        .IsUnique()
                        .HasDatabaseName("ux_configuracoes_distribuicao_vagas_processo_oferta");

                    b.ToTable("configuracoes_distribuicao_vagas", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.CriterioDesempate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Args")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("args");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<Guid>("ProcessoSeletivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("processo_seletivo_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_criterios_desempate");

                    b.HasIndex("ProcessoSeletivoId", "Ordem")
                        .IsUnique()
                        .HasDatabaseName("ux_criterios_desempate_processo_ordem");

                    b.ToTable("criterios_desempate", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.DocumentoEdital", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConfirmadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmado_em");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("HashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_sha256");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_key");

                    b.Property<string>("ObjectKeyConfirmado")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_key_confirmado");

                    b.Property<Guid>("ProcessoSeletivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("processo_seletivo_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long?>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_documentos_edital");

                    b.HasIndex("ProcessoSeletivoId")
                        .HasDatabaseName("ix_documentos_edital_processo_seletivo_id");

                    b.ToTable("documentos_edital", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.EtapaProcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Carater")
                        .HasColumnType("integer")
                        .HasColumnName("carater");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nome");

                    b.Property<decimal?>("NotaMinima")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("nota_minima");

                    b.Property<int?>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("peso");

                    b.Property<Guid>("ProcessoSeletivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("processo_seletivo_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_etapas_processo");

                    b.HasIndex("ProcessoSeletivoId", "Ordem")
                        .IsUnique()
                        .HasDatabaseName("ix_etapas_processo_processo_seletivo_id_ordem");

                    b.ToTable("etapas_processo", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ModalidadeSelecionada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcaoQuandoIndeferido")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("acao_quando_indeferido");

                    b.Property<string>("BaseLegal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_legal");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo");

                    b.Property<string>("ComposicaoOrigemCodigo")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("composicao_origem_codigo");

                    b.Property<string>("ComposicaoVagas")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("composicao_vagas");

                    b.Property<Guid>("ConfiguracaoDistribuicaoVagasId")
                        .HasColumnType("uuid")
                        .HasColumnName("configuracao_distribuicao_vagas_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CriteriosCumulativos")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("criterios_cumulativos")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("ModalidadeOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("modalidade_origem_id");

                    b.Property<string>("NaturezaLegal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("natureza_legal");

                    b.Property<string>("RegraRemanejamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("regra_remanejamento");

                    b.Property<string>("RemanejamentoDestino")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("remanejamento_destino");

                    b.Property<string>("RemanejamentoFallback")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("remanejamento_fallback");

                    b.Property<string>("RemanejamentoPar")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("remanejamento_par");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_modalidades_selecionadas");

                    b.HasIndex("ConfiguracaoDistribuicaoVagasId")
                        .HasDatabaseName("ix_modalidades_selecionadas_configuracao_distribuicao_vagas_id");

                    b.ToTable("modalidades_selecionadas", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ObrigatoriedadeLegal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AtoNormativoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ato_normativo_url");

                    b.Property<string>("BaseLegal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_legal");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("categoria");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DescricaoHumana")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao_humana");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("hash")
                        .IsFixedLength();

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PortariaInternaCodigo")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("portaria_interna_codigo");

                    b.Property<string>("Predicado")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("predicado");

                    b.Property<string>("RegraCodigo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("regra_codigo");

                    b.Property<string>("TipoEditalCodigo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tipo_edital_codigo");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly?>("VigenciaFim")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_fim");

                    b.Property<DateOnly>("VigenciaInicio")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_inicio");

                    b.HasKey("Id")
                        .HasName("pk_obrigatoriedades_legais");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ux_obrigatoriedades_legais_hash_ativos")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("RegraCodigo")
                        .IsUnique()
                        .HasDatabaseName("ux_obrigatoriedades_legais_regra_codigo_ativos")
                        .HasFilter("is_deleted = false");

                    b.ToTable("obrigatoriedades_legais", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ObrigatoriedadeLegalHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConteudoJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudo_json");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("hash")
                        .IsFixedLength();

                    b.Property<Guid>("RegraId")
                        .HasColumnType("uuid")
                        .HasColumnName("regra_id");

                    b.Property<DateTimeOffset>("SnapshotAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_at");

                    b.Property<string>("SnapshotBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("snapshot_by");

                    b.HasKey("Id")
                        .HasName("pk_obrigatoriedade_legal_historico");

                    b.HasIndex("RegraId", "SnapshotAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_obrigatoriedade_legal_historico_regra_snapshot_at");

                    b.ToTable("obrigatoriedade_legal_historico", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaAtendimentoEspecializado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProcessoSeletivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("processo_seletivo_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ofertas_atendimento_especializado");

                    b.HasIndex("ProcessoSeletivoId")
                        .IsUnique()
                        .HasDatabaseName("ix_ofertas_atendimento_especializado_processo_seletivo_id");

                    b.ToTable("ofertas_atendimento_especializado", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaCondicao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CondicaoCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("condicao_codigo");

                    b.Property<string>("CondicaoNome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("condicao_nome");

                    b.Property<Guid>("CondicaoOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("condicao_origem_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OfertaAtendimentoEspecializadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("oferta_atendimento_especializado_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ofertas_condicao");

                    b.HasIndex("OfertaAtendimentoEspecializadoId", "CondicaoOrigemId")
                        .IsUnique()
                        .HasDatabaseName("ix_ofertas_condicao_oferta_atendimento_especializado_id_condic");

                    b.ToTable("ofertas_condicao", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaRecurso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OfertaAtendimentoEspecializadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("oferta_atendimento_especializado_id");

                    b.Property<string>("RecursoNome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("recurso_nome");

                    b.Property<Guid>("RecursoOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurso_origem_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ofertas_recurso");

                    b.HasIndex("OfertaAtendimentoEspecializadoId", "RecursoOrigemId")
                        .IsUnique()
                        .HasDatabaseName("ix_ofertas_recurso_oferta_atendimento_especializado_id_recurso");

                    b.ToTable("ofertas_recurso", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaTipoDeficiencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OfertaAtendimentoEspecializadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("oferta_atendimento_especializado_id");

                    b.Property<string>("TipoDeficienciaNome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("tipo_deficiencia_nome");

                    b.Property<Guid>("TipoDeficienciaOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_deficiencia_origem_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ofertas_tipo_deficiencia");

                    b.HasIndex("OfertaAtendimentoEspecializadoId", "TipoDeficienciaOrigemId")
                        .IsUnique()
                        .HasDatabaseName("ix_ofertas_tipo_deficiencia_oferta_atendimento_especializado_i");

                    b.ToTable("ofertas_tipo_deficiencia", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nome");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_processos_seletivos");

                    b.ToTable("processos_seletivos", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.RascunhoRetificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbertoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aberto_em");

                    b.Property<string>("AbertoPorSub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("aberto_por_sub");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo");

                    b.Property<int>("NumeroVersaoBase")
                        .HasColumnType("integer")
                        .HasColumnName("numero_versao_base");

                    b.Property<Guid>("ProcessoSeletivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("processo_seletivo_id");

                    b.Property<int>("Revisao")
                        .HasColumnType("integer")
                        .HasColumnName("revisao");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VersaoBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("versao_base_id");

                    b.HasKey("Id")
                        .HasName("pk_rascunhos_retificacao");

                    b.HasIndex("ProcessoSeletivoId")
                        .IsUnique()
                        .HasDatabaseName("ux_rascunhos_retificacao_processo");

                    b.ToTable("rascunhos_retificacao", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.RegraCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseLegal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_legal");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EsquemaArgs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("esquema_args");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("hash")
                        .IsFixedLength();

                    b.Property<string>("Invariantes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("invariantes");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("versao");

                    b.HasKey("Id")
                        .HasName("pk_rol_de_regras");

                    b.HasIndex("Hash")
                        .HasDatabaseName("ix_rol_de_regras_hash");

                    b.HasIndex("Codigo", "Versao")
                        .IsUnique()
                        .HasDatabaseName("ux_rol_de_regras_codigo_versao");

                    b.ToTable("rol_de_regras", "selecao");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000001"),
                            BaseLegal = "Proposta CEPS + #56; média ponderada NOTA=Σ(nota×peso)/Σpeso",
                            Codigo = "FORMULA-MEDIA-PONDERADA",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{\"fonte_pesos\":[\"etapa\",\"peso_area_enem\"]}",
                            Hash = "a6fdc29bce533ef3cf8acb6cfdd7d67a99104541f6201d227f0d1c7051229ad6",
                            Invariantes = "[\"divisor = Σ(peso das etapas classificatória∪ambas)\"]",
                            Tipo = "regra_calculo",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000002"),
                            BaseLegal = "Portaria MEC 18/2012 art. 16 — SiSU federal (CEPS não calcula)",
                            Codigo = "CLASSIFICACAO-IMPORTADA",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{}",
                            Hash = "8e6f1f7b705c601991bf0617bbf881e39a3666c641abdfa4c1bd9ce2ecbcc85c",
                            Invariantes = "[\"sem cálculo local; classificação federal por importação do listão\"]",
                            Tipo = "regra_calculo",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000003"),
                            BaseLegal = "Decisão CEPS/PO (gaps 1.1) — truncamento 2 casas (default)",
                            Codigo = "PRECISAO-TRUNCAR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{\"casas\":\"integer\"}",
                            Hash = "66cbb932e61982f09fdd1d60a0db8411ea02dedc19bb72d1af23004f1e18360b",
                            Invariantes = "[\"trunca na N-ésima casa, sem arredondar\"]",
                            Tipo = "regra_arredondamento",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000004"),
                            BaseLegal = "Reprodução de editais antigos (PSE/Convênios)",
                            Codigo = "PRECISAO-ARREDONDAR-CIMA",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{\"casas\":\"integer\"}",
                            Hash = "efc491bf6a242a870c7bf9969048c198db88116ba39e72a44bcf1d5d5aebc4fb",
                            Invariantes = "[\"arredonda p/ cima se 3ª casa ≥ 5\"]",
                            Tipo = "regra_arredondamento",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000005"),
                            BaseLegal = "Edital por processo (nota mínima eliminatória)",
                            Codigo = "ELIM-NOTA-MINIMA-ETAPA",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{\"etapa\":\"text\",\"nota_minima\":\"numeric\"}",
                            Hash = "b64f643eba9744efc20bf19221bde85c645da32262a7d2ef616f18bd7c2ed5ac",
                            Invariantes = "[\"nota < mínima na etapa → elimina\"]",
                            Tipo = "regra_eliminacao",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000006"),
                            BaseLegal = "Res. 805/2024 Anexo I (corte de Redação = 400)",
                            Codigo = "ELIM-CORTE-REDACAO",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{\"minimo\":\"numeric\"}",
                            Hash = "6a23db02c00878d5bb98a445e8dc72e209a95f2aa4a8bfd91de8fa08ee69c240",
                            Invariantes = "[\"redação < mínimo → elimina\"]",
                            Tipo = "regra_eliminacao",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000007"),
                            BaseLegal = "Res. 805/2024 art. 5º (zero em qualquer área elimina)",
                            Codigo = "ELIM-ZERO-EM-AREA",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{}",
                            Hash = "75f4929b848138c8ed939a182e3664451ce38cd40a136adda438b62e1b6e3fb8",
                            Invariantes = "[\"nota zero em qualquer área do ENEM → elimina\"]",
                            Tipo = "regra_eliminacao",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000008"),
                            BaseLegal = "RN05 + decisão PO Jairo (×1,20 sem teto, após pesos)",
                            Codigo = "BONUS-MULTIPLICATIVO",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{\"fator\":\"numeric\",\"teto\":\"numeric|null\"}",
                            Hash = "d824fa64884e038e132f918dfd6efecf56d1df4cd4a1a1f86a78bf31718dae9b",
                            Invariantes = "[\"nota_final × fator, após os pesos; teto opcional\"]",
                            Tipo = "regra_bonus",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000009"),
                            BaseLegal = "Lei 10.741/2003 art. 27 (Estatuto do Idoso)",
                            Codigo = "DESEMPATE-IDOSO",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{\"idade_minima\":\"integer\"}",
                            Hash = "6738b1a9ca4f063f7f215cabb837e055d8abafaf0835f0b3deeed1c97f0becd4",
                            Invariantes = "[\"prioriza quem satisfaz FAIXA_ETARIA ≥ idade_minima\"]",
                            Tipo = "criterio_desempate",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000010"),
                            BaseLegal = "Edital (ordem de desempate)",
                            Codigo = "DESEMPATE-MAIOR-NOTA-ETAPA",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{\"etapa\":\"text\"}",
                            Hash = "1a988e6681b2970dc6c568c7372ceaf2f6e5ec0f7061ac47f656e1366a9ecad8",
                            Invariantes = "[\"ordena por maior nota da etapa indicada\"]",
                            Tipo = "criterio_desempate",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000011"),
                            BaseLegal = "Edital (maior idade cronológica)",
                            Codigo = "DESEMPATE-MAIOR-IDADE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{}",
                            Hash = "1efa26eaeffc88baf31ce9e2030c05c9976fae125e9845fe0283168050dc1237",
                            Invariantes = "[\"ordena por data de nascimento (nascido mais cedo vence)\"]",
                            Tipo = "criterio_desempate",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000012"),
                            BaseLegal = "Edital (critério adicional via fato do candidato — ex.: professor rural)",
                            Codigo = "DESEMPATE-PREDICADO-FATO",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{\"fato\":\"text\",\"operador\":\"text\",\"valor\":\"any\"}",
                            Hash = "d832d910826f25b6b50fd324f2f3cae472440c0e81e082be7c8d4fefe3de3f21",
                            Invariantes = "[\"prioriza quem satisfaz predicado sobre FatoCandidato; fato deve estar no vocabulário e ser coletado\"]",
                            Tipo = "criterio_desempate",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000013"),
                            BaseLegal = "RN04 (processamento de 1ª/2ª opção)",
                            Codigo = "ALOCACAO-OPCOES-RN04",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{\"n_opcoes\":\"integer\"}",
                            Hash = "2bb69f0e34483e635aa0903f8d3ba19a4255e8f542c5f7090ac75cecf200c988",
                            Invariantes = "[\"1ª opção → 2ª opção → remanejamento → lista de espera\"]",
                            Tipo = "regra_ordem_alocacao",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000014"),
                            BaseLegal = "Lei 12.711/2012 art. 1º parágrafo único (red. Lei 14.723/2023) — renda familiar bruta per capita ≤ 1 SM (ensino superior); PN MEC 18/2012 art. 6º-7º — apuração da renda mensal per capita + exclusões obrigatórias",
                            Codigo = "RENDA-PER-CAPITA-LEI-12711",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{\"limite_sm\":\"numeric\",\"sm_referencia\":\"numeric (SM congelado na data de início das inscrições)\",\"periodo_apuracao_meses\":\"integer (ex.: 3 últimos meses)\",\"criterio_media_mensal\":\"text (média mensal dos rendimentos brutos)\",\"exclusoes_renda\":\"lista (PN 18/2012 art. 7º)\",\"composicao_nucleo_familiar\":\"quem compõe o núcleo familiar\"}",
                            Hash = "5a1ad80627e354c03e4d6ef776a45db695a1203cea574a288dbcdf706ca58899",
                            Invariantes = "[\"média mensal da renda familiar bruta (últimos N meses, após exclusões) ÷ nº de membros do núcleo ≤ limite_sm × sm_referencia\"]",
                            Tipo = "regra_elegibilidade",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000015"),
                            BaseLegal = "Portaria Normativa MEC nº 18/2012 art. 10 e 11 (red. PN 2.027/2023) — distribuição e arredondamento das vagas reservadas; Lei 12.711/2012 (red. Lei 14.723/2023)",
                            Codigo = "DISTRIB-VAGAS-LEI-12711",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{\"pr_minimo\":\"numeric (piso 0,5 — art. 10 II; teto 1,0)\",\"modo_arredondamento\":\"teto (ceil) em todas as sub-reservas EXCETO LI_Q (floor) — art. 11\",\"ordem_garantia_minima\":[\"LB_PPI\",\"LB_Q\",\"LB_PCD\",\"LB_EP\",\"LI_PPI\",\"LI_PCD\",\"LI_EP\"],\"sub_reservas\":[\"PPI\",\"Q\",\"PCD\",\"EP\"],\"entradas_por_edital\":[\"VO_base\",\"PR\",\"ReferenciaReservaDemografica\"]}",
                            Hash = "0eb12ca67af16ab666e0db0894d795ec725422326cf7dedba2e804f496e0d807",
                            Invariantes = "[\"VR=ceil(VO×PR)\",\"VRRI=ceil(VR×0,5)\",\"VRSI=VR−VRRI\",\"sub-reservas ceil EXCETO LI_Q=floor (art. 11)\",\"garantia mín-1 ordenada I-VII condicional à disponibilidade (art. 10 §2º), LI_Q fora\",\"INV-3a: LB_EP≥0 e LI_EP≥0\",\"INV-3b: AC≥0\",\"INV-3c: VR_final+RETIRADAS+AC=VO_base\"]",
                            Tipo = "regra_distribuicao_vagas",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000016"),
                            BaseLegal = "Res. Unifesspa 532/2021 (vagas PcD/Indígena/Quilombola); Portaria MEC 18/2012 art. 12 (reservas suplementares e outras ações afirmativas)",
                            Codigo = "DISTRIB-VAGAS-INSTITUCIONAL",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{\"quadro_fixo_por_modalidade\":\"objeto {codigo: quantidade} fixado por edital (NÃO art. 10)\",\"aplicacao\":\"PSIQ (IND/QUIL) e PSE Ed. Campo — quadro institucional\"}",
                            Hash = "03b114eb3b559367b7d79f9edb1371f8164c5ede0c5f4b21809ee572c49c9451",
                            Invariantes = "[\"quadro fixo por edital (não recalculado pelo art. 10)\",\"modalidades institucionais somam conforme composicao_vagas (SUPLEMENTAR_AO_TOTAL ou RETIRA_DE)\"]",
                            Tipo = "regra_distribuicao_vagas",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000017"),
                            BaseLegal = "Portaria MEC 18/2012 art. 11, parágrafo único (red. PN 2.027/2023) — cap nas vagas da oferta + prioridade do inciso III (LB) sobre o inciso IV (LI); art. 10 II (mínimo 50%, piso)",
                            Codigo = "RECONCILIACAO-VAGAS-ART11-PU",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{\"reconciliacao_federal\":\"CAP_VO + PRIORIDADE_LB (art. 11 §único, embutida em DISTRIB-VAGAS-LEI-12711)\",\"motores_nao_art10\":\"REDUZIR_DE | REDUZIR_PROPORCIONAL_EM (apenas distribuições institucionais; clamp >=0; VEDADOS à Lei 12.711)\"}",
                            Hash = "ad2d8012ddc1f2ea4d763034899d07590c4a49901744b852dca2e70cede8b1e9",
                            Invariantes = "[\"cap em VO: a reserva nunca excede as vagas da oferta (art. 11 §único I)\",\"prioridade LB>LI: na escassez a LI cede primeiro (art. 11 §único II)\",\"estouro sobre o nominal 50% (VR) e LEGAL — piso (art. 10 II), absorvido pela AC\",\"curso pequeno e determinístico por lei (capa, não bloqueia)\"]",
                            Tipo = "regra_ajuste_distribuicao_vagas",
                            Versao = "v1"
                        },
                        new
                        {
                            Id = new Guid("d0a00000-0000-7000-8000-000000000018"),
                            BaseLegal = "Lei 9.784/1999 (processo administrativo federal); edital/processo (prazo configurável por edital); regimento CONSEPE (2ª instância)",
                            Codigo = "RECURSO-MULTI-INSTANCIA",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EsquemaArgs = "{\"prazo_valor\":\"numeric\",\"prazo_unidade\":\"HORAS|DIAS|DIAS_UTEIS (sem default — dado do edital)\",\"contra_ato\":\"codigo da fase produtora recorrível (NUNCA resultado definitivo)\",\"marco_inicial\":\"a partir de quando conta (ex.: publicacao_resultado)\",\"instancias\":\"lista ordenada [{instancia,dono,prazo_valor,prazo_unidade}] — 1ª CEPS, 2ª CONSEPE\"}",
                            Hash = "660cf3fffe22069f5a7f302a98b1e44b96d2e992680f02304935a36548f95490",
                            Invariantes = "[\"interposição GATED pela janela aberta (sem recurso a qualquer momento)\",\"sem recurso ao resultado definitivo (≠ recurso de habilitação CRCA)\",\"2ª instância (CONSEPE) só após indeferimento da 1ª; CONSEPE emite parecer externo, CEPS anexa e aplica (vinculante)\",\"processo PARALISA enquanto 2ª instância pendente; avanço só após expirar o prazo\",\"append-only: parecer/retificação = novo fato, não sobrescreve o passado\"]",
                            Tipo = "regra_prazo_recurso",
                            Versao = "v1"
                        });
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.RegraEliminacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Args")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("args");

                    b.Property<Guid>("ConfiguracaoClassificacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("configuracao_classificacao_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_regras_eliminacao");

                    b.HasIndex("ConfiguracaoClassificacaoId")
                        .HasDatabaseName("ix_regras_eliminacao_configuracao_classificacao_id");

                    b.ToTable("regras_eliminacao", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.VersaoConfiguracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlgoritmoHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("algoritmo_hash");

                    b.Property<string>("AtoCriadorHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("ato_criador_hash")
                        .IsFixedLength();

                    b.Property<Guid>("AtoCriadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("ato_criador_id");

                    b.Property<Guid?>("AtoCriadorRetificaId")
                        .HasColumnType("uuid")
                        .HasColumnName("ato_criador_retifica_id");

                    b.Property<string>("AtorUsuarioSub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ator_usuario_sub");

                    b.Property<string>("ConfiguracaoCongelada")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuracao_congelada");

                    b.Property<byte[]>("ConfiguracaoCongeladaCanonica")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("configuracao_congelada_canonica");

                    b.Property<string>("HashConfiguracao")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("hash_configuracao")
                        .IsFixedLength();

                    b.Property<int>("NumeroVersao")
                        .HasColumnType("integer")
                        .HasColumnName("numero_versao");

                    b.Property<Guid>("ProcessoSeletivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("processo_seletivo_id");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("schema_version");

                    b.Property<DateTimeOffset>("VigenteAPartirDe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_a_partir_de");

                    b.HasKey("Id")
                        .HasName("pk_versoes_configuracao");

                    b.HasIndex("AtoCriadorId")
                        .IsUnique()
                        .HasDatabaseName("ux_versoes_configuracao_ato_criador");

                    b.HasIndex("ProcessoSeletivoId", "NumeroVersao")
                        .IsUnique()
                        .HasDatabaseName("ux_versoes_configuracao_processo_numero");

                    b.HasIndex("ProcessoSeletivoId", "VigenteAPartirDe", "NumeroVersao")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_versoes_configuracao_processo_vigencia");

                    b.ToTable("versoes_configuracao", "selecao", t =>
                        {
                            t.HasCheckConstraint("ck_versoes_configuracao_ato_criador_hash", "ato_criador_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_versoes_configuracao_ato_criador_nao_zero", "ato_criador_id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_versoes_configuracao_contrato_abertura", "(numero_versao = 1 AND ato_criador_retifica_id IS NULL) OR (numero_versao > 1 AND ato_criador_retifica_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_versoes_configuracao_hash_configuracao", "hash_configuracao ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_versoes_configuracao_nao_autorretifica", "ato_criador_retifica_id IS NULL OR ato_criador_retifica_id <> ato_criador_id");

                            t.HasCheckConstraint("ck_versoes_configuracao_numero_positivo", "numero_versao > 0");
                        });
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ConfiguracaoBonusRegional", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", null)
                        .WithOne("BonusRegional")
                        .HasForeignKey("Unifesspa.UniPlus.Selecao.Domain.Entities.ConfiguracaoBonusRegional", "ProcessoSeletivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_configuracoes_bonus_regional_processos_seletivos_processo_s");

                    b.OwnsOne("Unifesspa.UniPlus.Selecao.Domain.ValueObjects.ReferenciaRegra", "Regra", b1 =>
                        {
                            b1.Property<Guid>("ConfiguracaoBonusRegionalId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("regra_codigo");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .HasColumnName("regra_hash")
                                .IsFixedLength();

                            b1.Property<string>("Versao")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("regra_versao");

                            b1.HasKey("ConfiguracaoBonusRegionalId");

                            b1.ToTable("configuracoes_bonus_regional", "selecao");

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracaoBonusRegionalId")
                                .HasConstraintName("fk_configuracoes_bonus_regional_configuracoes_bonus_regional_id");
                        });

                    b.Navigation("Regra")
                        .IsRequired();
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ConfiguracaoClassificacao", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", null)
                        .WithOne("Classificacao")
                        .HasForeignKey("Unifesspa.UniPlus.Selecao.Domain.Entities.ConfiguracaoClassificacao", "ProcessoSeletivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_configuracoes_classificacao_processos_seletivos_processo_se");

                    b.OwnsOne("Unifesspa.UniPlus.Selecao.Domain.ValueObjects.ReferenciaRegra", "RegraArredondamento", b1 =>
                        {
                            b1.Property<Guid>("ConfiguracaoClassificacaoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("regra_arredondamento_codigo");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .HasColumnName("regra_arredondamento_hash")
                                .IsFixedLength();

                            b1.Property<string>("Versao")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("regra_arredondamento_versao");

                            b1.HasKey("ConfiguracaoClassificacaoId");

                            b1.ToTable("configuracoes_classificacao", "selecao");

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracaoClassificacaoId")
                                .HasConstraintName("fk_configuracoes_classificacao_configuracoes_classificacao_id");
                        });

                    b.OwnsOne("Unifesspa.UniPlus.Selecao.Domain.ValueObjects.ReferenciaRegra", "RegraCalculo", b1 =>
                        {
                            b1.Property<Guid>("ConfiguracaoClassificacaoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("regra_calculo_codigo");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .HasColumnName("regra_calculo_hash")
                                .IsFixedLength();

                            b1.Property<string>("Versao")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("regra_calculo_versao");

                            b1.HasKey("ConfiguracaoClassificacaoId");

                            b1.ToTable("configuracoes_classificacao", "selecao");

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracaoClassificacaoId")
                                .HasConstraintName("fk_configuracoes_classificacao_configuracoes_classificacao_id");
                        });

                    b.OwnsOne("Unifesspa.UniPlus.Selecao.Domain.ValueObjects.ReferenciaRegra", "RegraOrdemAlocacao", b1 =>
                        {
                            b1.Property<Guid>("ConfiguracaoClassificacaoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("regra_ordem_alocacao_codigo");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .HasColumnName("regra_ordem_alocacao_hash")
                                .IsFixedLength();

                            b1.Property<string>("Versao")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("regra_ordem_alocacao_versao");

                            b1.HasKey("ConfiguracaoClassificacaoId");

                            b1.ToTable("configuracoes_classificacao", "selecao");

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracaoClassificacaoId")
                                .HasConstraintName("fk_configuracoes_classificacao_configuracoes_classificacao_id");
                        });

                    b.Navigation("RegraArredondamento");

                    b.Navigation("RegraCalculo")
                        .IsRequired();

                    b.Navigation("RegraOrdemAlocacao")
                        .IsRequired();
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ConfiguracaoDistribuicaoVagas", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", null)
                        .WithMany("DistribuicaoVagas")
                        .HasForeignKey("ProcessoSeletivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_configuracoes_distribuicao_vagas_processos_seletivos_proces");

                    b.OwnsOne("Unifesspa.UniPlus.Selecao.Domain.ValueObjects.ReferenciaRegra", "RegraDistribuicao", b1 =>
                        {
                            b1.Property<Guid>("ConfiguracaoDistribuicaoVagasId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("regra_distribuicao_codigo");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .HasColumnName("regra_distribuicao_hash")
                                .IsFixedLength();

                            b1.Property<string>("Versao")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("regra_distribuicao_versao");

                            b1.HasKey("ConfiguracaoDistribuicaoVagasId");

                            b1.ToTable("configuracoes_distribuicao_vagas", "selecao");

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracaoDistribuicaoVagasId")
                                .HasConstraintName("fk_configuracoes_distribuicao_vagas_configuracoes_distribuicao");
                        });

                    b.OwnsOne("Unifesspa.UniPlus.Selecao.Domain.ValueObjects.ReferenciaReservaDemograficaSnapshot", "ReferenciaDemografica", b1 =>
                        {
                            b1.Property<Guid>("ConfiguracaoDistribuicaoVagasId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("BaseLegal")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("referencia_demografica_base_legal");

                            b1.Property<string>("CensoReferencia")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("referencia_demografica_censo");

                            b1.Property<Guid>("OrigemId")
                                .HasColumnType("uuid")
                                .HasColumnName("referencia_demografica_origem_id");

                            b1.Property<decimal>("PcdPercentual")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("referencia_demografica_pcd_percentual");

                            b1.Property<decimal>("PpiPercentual")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("referencia_demografica_ppi_percentual");

                            b1.Property<decimal>("QuilombolaPercentual")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("referencia_demografica_quilombola_percentual");

                            b1.HasKey("ConfiguracaoDistribuicaoVagasId");

                            b1.ToTable("configuracoes_distribuicao_vagas", "selecao");

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracaoDistribuicaoVagasId")
                                .HasConstraintName("fk_configuracoes_distribuicao_vagas_configuracoes_distribuicao");
                        });

                    b.Navigation("ReferenciaDemografica");

                    b.Navigation("RegraDistribuicao")
                        .IsRequired();
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.CriterioDesempate", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", null)
                        .WithMany("CriteriosDesempate")
                        .HasForeignKey("ProcessoSeletivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_criterios_desempate_processos_seletivos_processo_seletivo_id");

                    b.OwnsOne("Unifesspa.UniPlus.Selecao.Domain.ValueObjects.ReferenciaRegra", "Regra", b1 =>
                        {
                            b1.Property<Guid>("CriterioDesempateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("regra_codigo");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .HasColumnName("regra_hash")
                                .IsFixedLength();

                            b1.Property<string>("Versao")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("regra_versao");

                            b1.HasKey("CriterioDesempateId");

                            b1.ToTable("criterios_desempate", "selecao");

                            b1.WithOwner()
                                .HasForeignKey("CriterioDesempateId")
                                .HasConstraintName("fk_criterios_desempate_criterios_desempate_id");
                        });

                    b.Navigation("Regra")
                        .IsRequired();
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.DocumentoEdital", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", null)
                        .WithMany()
                        .HasForeignKey("ProcessoSeletivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documentos_edital_processos_seletivos_processo_seletivo_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.EtapaProcesso", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", null)
                        .WithMany("Etapas")
                        .HasForeignKey("ProcessoSeletivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_etapas_processo_processos_seletivos_processo_seletivo_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ModalidadeSelecionada", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.ConfiguracaoDistribuicaoVagas", null)
                        .WithMany("Modalidades")
                        .HasForeignKey("ConfiguracaoDistribuicaoVagasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modalidades_selecionadas_configuracoes_distribuicao_vagas_c");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ObrigatoriedadeLegalHistorico", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.ObrigatoriedadeLegal", null)
                        .WithMany()
                        .HasForeignKey("RegraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_obrigatoriedade_legal_historico_regra_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaAtendimentoEspecializado", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", null)
                        .WithOne("OfertaAtendimento")
                        .HasForeignKey("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaAtendimentoEspecializado", "ProcessoSeletivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ofertas_atendimento_especializado_processos_seletivos_proce");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaCondicao", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaAtendimentoEspecializado", null)
                        .WithMany("Condicoes")
                        .HasForeignKey("OfertaAtendimentoEspecializadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ofertas_condicao_ofertas_atendimento_especializado_oferta_a");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaRecurso", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaAtendimentoEspecializado", null)
                        .WithMany("Recursos")
                        .HasForeignKey("OfertaAtendimentoEspecializadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ofertas_recurso_ofertas_atendimento_especializado_oferta_at");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaTipoDeficiencia", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaAtendimentoEspecializado", null)
                        .WithMany("TiposDeficiencia")
                        .HasForeignKey("OfertaAtendimentoEspecializadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ofertas_tipo_deficiencia_ofertas_atendimento_especializado_");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.RascunhoRetificacao", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", null)
                        .WithOne("Rascunho")
                        .HasForeignKey("Unifesspa.UniPlus.Selecao.Domain.Entities.RascunhoRetificacao", "ProcessoSeletivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rascunhos_retificacao_processos_seletivos_processo_seletivo");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.RegraEliminacao", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.ConfiguracaoClassificacao", null)
                        .WithMany("RegrasEliminacao")
                        .HasForeignKey("ConfiguracaoClassificacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_regras_eliminacao_configuracoes_classificacao_configuracao_");

                    b.OwnsOne("Unifesspa.UniPlus.Selecao.Domain.ValueObjects.ReferenciaRegra", "Regra", b1 =>
                        {
                            b1.Property<Guid>("RegraEliminacaoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("regra_codigo");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .HasColumnName("regra_hash")
                                .IsFixedLength();

                            b1.Property<string>("Versao")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("regra_versao");

                            b1.HasKey("RegraEliminacaoId");

                            b1.ToTable("regras_eliminacao", "selecao");

                            b1.WithOwner()
                                .HasForeignKey("RegraEliminacaoId")
                                .HasConstraintName("fk_regras_eliminacao_regras_eliminacao_id");
                        });

                    b.Navigation("Regra")
                        .IsRequired();
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.VersaoConfiguracao", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", null)
                        .WithMany()
                        .HasForeignKey("ProcessoSeletivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_versoes_configuracao_processo");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ConfiguracaoClassificacao", b =>
                {
                    b.Navigation("RegrasEliminacao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ConfiguracaoDistribuicaoVagas", b =>
                {
                    b.Navigation("Modalidades");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaAtendimentoEspecializado", b =>
                {
                    b.Navigation("Condicoes");

                    b.Navigation("Recursos");

                    b.Navigation("TiposDeficiencia");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", b =>
                {
                    b.Navigation("BonusRegional");

                    b.Navigation("Classificacao");

                    b.Navigation("CriteriosDesempate");

                    b.Navigation("DistribuicaoVagas");

                    b.Navigation("Etapas");

                    b.Navigation("OfertaAtendimento");

                    b.Navigation("Rascunho");
                });
#pragma warning restore 612, 618
        }
    }
}
