// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unifesspa.UniPlus.Selecao.Infrastructure.Persistence;

#nullable disable

namespace Unifesspa.UniPlus.Selecao.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SelecaoDbContext))]
    partial class SelecaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("selecao")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Unifesspa.UniPlus.Infrastructure.Core.Idempotency.IdempotencyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("body_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("idempotency_key");

                    b.Property<byte[]>("ResponseBodyCipher")
                        .HasColumnType("bytea")
                        .HasColumnName("response_body_cipher");

                    b.Property<string>("ResponseHeadersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_headers_json");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("scope");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_cache");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_idempotency_expires_at");

                    b.HasIndex("Scope", "Endpoint", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("idx_idempotency_lookup");

                    b.ToTable("idempotency_cache", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Candidato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_candidatos");

                    b.ToTable("candidatos", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Cota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EditalId")
                        .HasColumnType("uuid")
                        .HasColumnName("edital_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Modalidade")
                        .HasColumnType("integer")
                        .HasColumnName("modalidade");

                    b.Property<decimal>("PercentualVagas")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentual_vagas");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cotas");

                    b.HasIndex("EditalId")
                        .HasDatabaseName("ix_cotas_edital_id");

                    b.ToTable("cotas", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Edital", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BonusRegionalHabilitado")
                        .HasColumnType("boolean")
                        .HasColumnName("bonus_regional_habilitado");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MaximoOpcoesCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("maximo_opcoes_curso");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TipoEditalId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_edital_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("titulo");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_editais");

                    b.ToTable("editais", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.EditalGovernanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EditalId")
                        .HasColumnType("uuid")
                        .HasColumnName("edital_id");

                    b.Property<string>("RegrasJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("regras_json");

                    b.Property<DateTimeOffset>("SnapshottedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshotted_at");

                    b.HasKey("Id")
                        .HasName("pk_edital_governance_snapshot");

                    b.HasIndex("EditalId")
                        .HasDatabaseName("ix_edital_governance_snapshot_edital_id");

                    b.ToTable("edital_governance_snapshot", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Etapa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("EditalId")
                        .HasColumnType("uuid")
                        .HasColumnName("edital_id");

                    b.Property<bool>("Eliminatoria")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminatoria");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<decimal?>("NotaMinima")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nota_minima");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<decimal>("Peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("peso");

                    b.Property<Guid?>("TipoEtapaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_etapa_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_etapas");

                    b.HasIndex("EditalId")
                        .HasDatabaseName("ix_etapas_edital_id");

                    b.ToTable("etapas", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.EtapaProcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Carater")
                        .HasColumnType("integer")
                        .HasColumnName("carater");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nome");

                    b.Property<decimal?>("NotaMinima")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("nota_minima");

                    b.Property<int?>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("peso");

                    b.Property<Guid>("ProcessoSeletivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("processo_seletivo_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_etapas_processo");

                    b.HasIndex("ProcessoSeletivoId", "Ordem")
                        .IsUnique()
                        .HasDatabaseName("ix_etapas_processo_processo_seletivo_id_ordem");

                    b.ToTable("etapas_processo", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Inscricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidato_id");

                    b.Property<string>("CodigoCursoPrimeiraOpcao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_curso_primeira_opcao");

                    b.Property<string>("CodigoCursoSegundaOpcao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_curso_segunda_opcao");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("EditalId")
                        .HasColumnType("uuid")
                        .HasColumnName("edital_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("ListaEspera")
                        .HasColumnType("boolean")
                        .HasColumnName("lista_espera");

                    b.Property<int>("Modalidade")
                        .HasColumnType("integer")
                        .HasColumnName("modalidade");

                    b.Property<string>("NumeroInscricao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_inscricao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inscricoes");

                    b.HasIndex("NumeroInscricao")
                        .IsUnique()
                        .HasDatabaseName("ix_inscricoes_numero_inscricao");

                    b.HasIndex("CandidatoId", "EditalId")
                        .HasDatabaseName("ix_inscricoes_candidato_id_edital_id");

                    b.ToTable("inscricoes", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ObrigatoriedadeLegal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AtoNormativoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ato_normativo_url");

                    b.Property<string>("BaseLegal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_legal");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("categoria");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DescricaoHumana")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao_humana");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("hash")
                        .IsFixedLength();

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PortariaInternaCodigo")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("portaria_interna_codigo");

                    b.Property<string>("Predicado")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("predicado");

                    b.Property<string>("RegraCodigo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("regra_codigo");

                    b.Property<string>("TipoEditalCodigo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tipo_edital_codigo");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly?>("VigenciaFim")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_fim");

                    b.Property<DateOnly>("VigenciaInicio")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_inicio");

                    b.HasKey("Id")
                        .HasName("pk_obrigatoriedades_legais");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ux_obrigatoriedades_legais_hash_ativos")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("RegraCodigo")
                        .IsUnique()
                        .HasDatabaseName("ux_obrigatoriedades_legais_regra_codigo_ativos")
                        .HasFilter("is_deleted = false");

                    b.ToTable("obrigatoriedades_legais", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ObrigatoriedadeLegalHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConteudoJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudo_json");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("hash")
                        .IsFixedLength();

                    b.Property<Guid>("RegraId")
                        .HasColumnType("uuid")
                        .HasColumnName("regra_id");

                    b.Property<DateTimeOffset>("SnapshotAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_at");

                    b.Property<string>("SnapshotBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("snapshot_by");

                    b.HasKey("Id")
                        .HasName("pk_obrigatoriedade_legal_historico");

                    b.HasIndex("RegraId", "SnapshotAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_obrigatoriedade_legal_historico_regra_snapshot_at");

                    b.ToTable("obrigatoriedade_legal_historico", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaAtendimentoEspecializado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProcessoSeletivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("processo_seletivo_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ofertas_atendimento_especializado");

                    b.HasIndex("ProcessoSeletivoId")
                        .IsUnique()
                        .HasDatabaseName("ix_ofertas_atendimento_especializado_processo_seletivo_id");

                    b.ToTable("ofertas_atendimento_especializado", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaCondicao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CondicaoCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("condicao_codigo");

                    b.Property<string>("CondicaoNome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("condicao_nome");

                    b.Property<Guid>("CondicaoOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("condicao_origem_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OfertaAtendimentoEspecializadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("oferta_atendimento_especializado_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ofertas_condicao");

                    b.HasIndex("OfertaAtendimentoEspecializadoId", "CondicaoOrigemId")
                        .IsUnique()
                        .HasDatabaseName("ix_ofertas_condicao_oferta_atendimento_especializado_id_condic");

                    b.ToTable("ofertas_condicao", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaRecurso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OfertaAtendimentoEspecializadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("oferta_atendimento_especializado_id");

                    b.Property<string>("RecursoNome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("recurso_nome");

                    b.Property<Guid>("RecursoOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurso_origem_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ofertas_recurso");

                    b.HasIndex("OfertaAtendimentoEspecializadoId", "RecursoOrigemId")
                        .IsUnique()
                        .HasDatabaseName("ix_ofertas_recurso_oferta_atendimento_especializado_id_recurso");

                    b.ToTable("ofertas_recurso", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaTipoDeficiencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OfertaAtendimentoEspecializadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("oferta_atendimento_especializado_id");

                    b.Property<string>("TipoDeficienciaNome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("tipo_deficiencia_nome");

                    b.Property<Guid>("TipoDeficienciaOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_deficiencia_origem_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ofertas_tipo_deficiencia");

                    b.HasIndex("OfertaAtendimentoEspecializadoId", "TipoDeficienciaOrigemId")
                        .IsUnique()
                        .HasDatabaseName("ix_ofertas_tipo_deficiencia_oferta_atendimento_especializado_i");

                    b.ToTable("ofertas_tipo_deficiencia", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nome");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_processos_seletivos");

                    b.ToTable("processos_seletivos", "selecao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Candidato", b =>
                {
                    b.OwnsOne("Unifesspa.UniPlus.Kernel.Domain.ValueObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("CandidatoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("cpf");

                            b1.HasKey("CandidatoId");

                            b1.HasIndex("Valor")
                                .IsUnique()
                                .HasDatabaseName("ix_candidatos_cpf");

                            b1.ToTable("candidatos", "selecao");

                            b1.WithOwner()
                                .HasForeignKey("CandidatoId")
                                .HasConstraintName("fk_candidatos_candidatos_id");
                        });

                    b.OwnsOne("Unifesspa.UniPlus.Kernel.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CandidatoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("email");

                            b1.HasKey("CandidatoId");

                            b1.ToTable("candidatos", "selecao");

                            b1.WithOwner()
                                .HasForeignKey("CandidatoId")
                                .HasConstraintName("fk_candidatos_candidatos_id");
                        });

                    b.OwnsOne("Unifesspa.UniPlus.Kernel.Domain.ValueObjects.NomeSocial", "NomeSocial", b1 =>
                        {
                            b1.Property<Guid>("CandidatoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Nome")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("nome_social");

                            b1.Property<string>("NomeCivil")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("nome_civil");

                            b1.HasKey("CandidatoId");

                            b1.ToTable("candidatos", "selecao");

                            b1.WithOwner()
                                .HasForeignKey("CandidatoId")
                                .HasConstraintName("fk_candidatos_candidatos_id");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("NomeSocial")
                        .IsRequired();
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Cota", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.Edital", null)
                        .WithMany("Cotas")
                        .HasForeignKey("EditalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cotas_editais_edital_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Edital", b =>
                {
                    b.OwnsOne("Unifesspa.UniPlus.Selecao.Domain.ValueObjects.FormulaCalculo", "FormulaCalculo", b1 =>
                        {
                            b1.Property<Guid>("EditalId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("BonusRegionalPercentual")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("bonus_regional_percentual");

                            b1.Property<decimal>("FatorDivisao")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("fator_divisao");

                            b1.HasKey("EditalId");

                            b1.ToTable("editais", "selecao");

                            b1.WithOwner()
                                .HasForeignKey("EditalId")
                                .HasConstraintName("fk_editais_editais_id");
                        });

                    b.OwnsOne("Unifesspa.UniPlus.Selecao.Domain.ValueObjects.NumeroEdital", "NumeroEdital", b1 =>
                        {
                            b1.Property<Guid>("EditalId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Ano")
                                .HasColumnType("integer")
                                .HasColumnName("ano_edital");

                            b1.Property<int>("Numero")
                                .HasColumnType("integer")
                                .HasColumnName("numero_edital");

                            b1.HasKey("EditalId");

                            b1.ToTable("editais", "selecao");

                            b1.WithOwner()
                                .HasForeignKey("EditalId")
                                .HasConstraintName("fk_editais_editais_id");
                        });

                    b.OwnsOne("Unifesspa.UniPlus.Selecao.Domain.ValueObjects.PeriodoInscricao", "PeriodoInscricao", b1 =>
                        {
                            b1.Property<Guid>("EditalId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("Fim")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("periodo_inscricao_fim");

                            b1.Property<DateTimeOffset>("Inicio")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("periodo_inscricao_inicio");

                            b1.HasKey("EditalId");

                            b1.ToTable("editais", "selecao");

                            b1.WithOwner()
                                .HasForeignKey("EditalId")
                                .HasConstraintName("fk_editais_editais_id");
                        });

                    b.Navigation("FormulaCalculo");

                    b.Navigation("NumeroEdital")
                        .IsRequired();

                    b.Navigation("PeriodoInscricao");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.EditalGovernanceSnapshot", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.Edital", null)
                        .WithMany()
                        .HasForeignKey("EditalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_edital_governance_snapshot_edital_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Etapa", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.Edital", null)
                        .WithMany("Etapas")
                        .HasForeignKey("EditalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_etapas_editais_edital_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.EtapaProcesso", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", null)
                        .WithMany("Etapas")
                        .HasForeignKey("ProcessoSeletivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_etapas_processo_processos_seletivos_processo_seletivo_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ObrigatoriedadeLegalHistorico", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.ObrigatoriedadeLegal", null)
                        .WithMany()
                        .HasForeignKey("RegraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_obrigatoriedade_legal_historico_regra_id");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaAtendimentoEspecializado", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", null)
                        .WithOne("OfertaAtendimento")
                        .HasForeignKey("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaAtendimentoEspecializado", "ProcessoSeletivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ofertas_atendimento_especializado_processos_seletivos_proce");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaCondicao", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaAtendimentoEspecializado", null)
                        .WithMany("Condicoes")
                        .HasForeignKey("OfertaAtendimentoEspecializadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ofertas_condicao_ofertas_atendimento_especializado_oferta_a");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaRecurso", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaAtendimentoEspecializado", null)
                        .WithMany("Recursos")
                        .HasForeignKey("OfertaAtendimentoEspecializadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ofertas_recurso_ofertas_atendimento_especializado_oferta_at");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaTipoDeficiencia", b =>
                {
                    b.HasOne("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaAtendimentoEspecializado", null)
                        .WithMany("TiposDeficiencia")
                        .HasForeignKey("OfertaAtendimentoEspecializadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ofertas_tipo_deficiencia_ofertas_atendimento_especializado_");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.Edital", b =>
                {
                    b.Navigation("Cotas");

                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.OfertaAtendimentoEspecializado", b =>
                {
                    b.Navigation("Condicoes");

                    b.Navigation("Recursos");

                    b.Navigation("TiposDeficiencia");
                });

            modelBuilder.Entity("Unifesspa.UniPlus.Selecao.Domain.Entities.ProcessoSeletivo", b =>
                {
                    b.Navigation("Etapas");

                    b.Navigation("OfertaAtendimento");
                });
#pragma warning restore 612, 618
        }
    }
}
